FeatureBaseDB/featurebase

index.go, index_test.go, pilosa.go
=> Prevent row labels that match the column label.

README.md
=> Link Contributing guide to file in repo instead of external site

executor.go, executor_test.go
=> Support inverse Range() queries.

Dockerfile
This utilizes Docker multi-stage builds to produce a minimal Docker image. Requires Docker 17.05.0.
=> Use Docker multi-stage build in Dockerfile

webui/assets/main.js, webui/assets/style.css, webui/index.html
=> Add syntax hints tooltip to WebUI

docs/administration.md, docs/api-reference.md, docs/client-libraries.md, docs/configuration.md, docs/data-model.md, docs/faq.md, docs/getting-started.md, docs/glossary.md, docs/installation.md, docs/introduction.md, docs/pdk.md, docs/query-language.md, docs/tutorials.md, docs/webui.md
The website build process is now able to download the docs from this repo.
=> Move docs into repo

roaring/roaring.go, roaring/roaring_internal_test.go
Looks like todd was right and CountRange isn't actually used, but here's the PR anyway.
=> Bitmap count rangev0.2

cmd/root.go, cmd/root_test.go
I spent a lot of time on using reflection to get valid config tag and just realized that I don't need it for validate field so I removed that part.
=> 33 validate config

fragment.go
This pull request adds a `"rows"` gauge that tracks the maximum row for each fragment. I originally tried to add a `"columns"` gauge too but I couldn't get it to quickly compute the max on start-up without scanning all the data files.
I also changed the `"maxSlice"` stat from a `count` to a `gauge`. Previously it was tracking the number of fragments created instead of the maximum slice.
Fixes #421.
=> Add statsd gauges for row count.

webui/assets/main.js
The first commit should definitely be taken, without it the completion is a little broken. This can close #235.
The second commit is a minor cleanup that I would like to include. It also simplifies the things that are started in the third commit (dynamic keywords, UI element showing possible completions), which we can do later, or never.
=> Autocomplete improvements

webui/assets/main.js, webui/assets/style.css, webui/index.html
Just a few minor fixes to styles and help text.
=> Webui fixes

roaring/roaring.go, roaring/roaring_test.go
=> added xor support to roaring

docs/administration.md, docs/configuration.md, server/server_test.go
=> StatsD documentation

.github/PULL_REQUEST_TEMPLATE.md
Fixes https://github.com/pilosa/general/issues/20
=> Add PULL_REQUEST_TEMPLATE file.

docs/administration.md, server.go, server/server_test.go
Count open file handles as a StatsD metric.
TODO: Does not work on Windows.
Fixes #
429
=> Count open file handles as a StatsD metric.

roaring/roaring.go, roaring/roaring_internal_test.go
backports performance fix to v0.2
Fixes #
=> rewrite intersectCountArrayBitmap for perf test

handler.go, handler_test.go, index.go, index_test.go, input_definition.go, input_definition_test.go, server.go
Use the internal.inputdefinition object for broadcasting to other nodes.  Create encoding methods to translate the JSON request to create a definition.
=> Use the internal.inputdefinition

handler.go, handler_test.go, index.go, index_test.go, input_definition.go, input_definition_test.go
=> add validation for input definition fields

roaring/roaring.go, roaring/roaring_test.go
also adds more test coverage for `differenceArrayRun`
=> bug fix in `differenceArrayRun` logic.

handler.go, handler_test.go, index.go, index_test.go, input_definition.go, input_definition_test.go
This PR handle #609, #656, #657, #658
Fixes #
=> Handle actions and execute SetBit

handler.go, input_definition.go, input_definition_test.go
Code cleanup, and prefaced validValueDestination values
=> Prefaced validValueDestination values

Makefile
This fixes `make cover-pkg` on GNU systems.
=> Add `-n` to tail command for GNU-tail compatibility

handler.go, handler_test.go, index.go, index_test.go, input_definition.go, input_definition_test.go
Handle the case where an action evaluates to a nil bit
=> Input nil bit

input_definition.go, input_definition_test.go
More Input definition error condition testing
- [x I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
=> Input tests

docs/api-reference.md
Replaces code-formatted section headers with readable words, which improves styling and makes anchor links less messy.
Addresses https://github.com/pilosa/www/issues/115
=> Replace code headers with anchor headers

docs/api-reference.md, docs/data-model.md
Adds brief description of undocumented query args `time_granularity` and `slices`. 
Addresses #591 
=> Docs query args

docs/query-language.md
Uses larger headers on the query language page for better separation.
Addresses https://github.com/pilosa/www/issues/115
=> Increase header sizes

docs/api-reference.md
API docs for input definition endpoints
=> API docs for input definition

docs/getting-started.md
Adding doc for using input-definition and input endpoints to ingest data
=> update input definition doc

docs/query-language.md
Added documentation describing the various caveats with the frame cache.  This should explain the TopN behavior in those edge cases
=> frame cache caveats documentation

handler.go, handler_test.go
=> skip null field when ingest data

CONTRIBUTING.md
Makes new "newcomer" github label a bit more visible.
=> Add link to newcomer label in CONTRIBUTING.md

docs/installation.md
=> add make generate-statik to docs

cache.go, fragment.go, fragment_test.go, frame.go, index.go, index_test.go
Implement Cache interface for NopCache to handle cacheType = "none"
=> None type cache

Makefile
Run `touch vendor` in `make vendor` so that `dep ensure` is only run when needed.
=> Run `touch vendor` in `make vendor`

docs/getting-started.md, docs/input-definition.md
separate input definition docs from getting started
=> separate input definition docs from getting started

docs/administration.md, docs/getting-started.md, holder.go
Attempt to set open file limit during Pilosa startup.
Fixes #722
=> Attempt to set open file limit during Pilosa startup. Fixes #722.

CHANGELOG.md, docs/api-reference.md, docs/installation.md
This applies the changes for Pilosa 0.5.0 to the master branch.
=> Release 0.5.0

CHANGELOG.md, docs/api-reference.md, docs/installation.md
=> Release v0.6.0

docs/architecture.md, roaring/roaring.go
Updated the docs page to reflect the latest storage format, and removed some cruft in roaring.go related to that.
Note that I also changed the cookie value to 12348, instead of the 12346 we were using previously. Aside from the binary incompatibility we've always had with the spec, the file format is now incompatible with previous Pilosa files, as well as logically different from both the spec and our old version. I think that warrants a different cookie, but if there is an argument against it I'll revert this and we can discuss.
With this change, any future changes to the format should be reflected in storageVersion, with the same cookie value.
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be …
=> Roaring minor fixes

pql/ast.go, pql/parser.go, pql/parser_test.go, pql/scanner.go, pql/scanner_test.go, pql/token.go
This adds conditional fields to PQL calls to support `Range()`. The original issue specified multiple arguments but I find this a lot clearer. Let me know if you want me to revert it back to the original.
Fixes #620 
=> Support PQL Range() queries for fields.

docs/administration.md, docs/api-reference.md, docs/client-libraries.md, docs/configuration.md, docs/data-model.md, docs/faq.md, docs/getting-started.md, docs/glossary.md, docs/installation.md, docs/introduction.md, docs/pdk.md, docs/query-language.md, docs/tutorials.md, docs/webui.md
This enables the website to automatically generate the navigation.
=> Add metadata to doc pages (version 0.4.x)

docs/administration.md, docs/api-reference.md, docs/client-libraries.md, docs/configuration.md, docs/data-model.md, docs/faq.md, docs/getting-started.md, docs/glossary.md, docs/input-definition.md, docs/installation.md, docs/introduction.md, docs/pdk.md, docs/query-language.md, docs/tutorials.md, docs/webui.md
This enables the website to automatically generate the navigation.
=> Add metadata to doc pages (version 0.5.x)

docs/administration.md, docs/api-reference.md, docs/client-libraries.md, docs/configuration.md, docs/data-model.md, docs/faq.md, docs/getting-started.md, docs/glossary.md, docs/input-definition.md, docs/installation.md, docs/introduction.md, docs/pdk.md, docs/query-language.md, docs/tutorials.md, docs/webui.md
This enables the website to automatically generate the navigation.
=> Add metadata to doc pages (version 0.6.x)

docs/architecture.md
This adds sorting and navigation metadata for the architecture document.
=> Doc metadata for Architecture doc (v0.6)

docs/administration.md, docs/api-reference.md, docs/architecture.md, docs/client-libraries.md, docs/configuration.md, docs/data-model.md, docs/faq.md, docs/getting-started.md, docs/glossary.md, docs/input-definition.md, docs/installation.md, docs/introduction.md, docs/pdk.md, docs/query-language.md, docs/tutorials.md, docs/webui.md
This adds metadata to the documentation for sorting and navigation.
=> Doc metadata

roaring/roaring.go
=> fix for #770

gossip/gossip.go
=> re-arrange GossipNodeSet.Open to hopefully avoid race

bitmap.go, bitmap_test.go, executor.go, executor_test.go
Add PQL support for the existing xor functions
=> Xor support for PQL

cache.go, cache_test.go
When Top value == threshold value the whole rank cache gets deleted
=> account for all same values in rank

.travis.yml
=> remove go1.7 from travis

docs/tutorials.md
I moved two repos to the pilosa organization, and updated references to those here and elsewhere.
@codysoyland it's not necessary, but if I wanted to make these updates in all docs versions, would I need a PR for each version branch?
=> Update repo url

Gopkg.lock, ctl/export_test.go, ctl/import_test.go, ctl/restore_test.go
=> use context everywhere instead of golang.org version

docs/configuration.md
We had some confusion over configuration - hopefully this will help to address it.
=> add cluster config example to docs

.travis.yml, fragment.go, roaring/roaring.go
=> Zero Alloc WriteTo

frame.go, handler.go, handler_test.go, pilosa.go
Provides an HTTP API for creating new fields on an existing frame.
Fixes #623
=> Field HTTP API

executor.go, executor_test.go
Fixed Sum call to return SumCount; removed Average call.
Fixes #821, #822
=> Fixes Sum call response; resolves #821, resolves #822

cmd/server.go
=> Handles SIGTERM signal; resolves #827

docs/query-language.md, executor.go, executor_test.go
=> TRIVIAL: SetColumnAttrs excludes frame attribute; resolves #792

docs/configuration.md
=> TRIVIAL: Fixes gossip-seed configuration example

docs/client-libraries.md
Updates Client Libraries section of the docs
=> Updated client library docs

fragment.go, roaring/roaring.go
=> Reuse container storage on UnmarshalBinary to improve memory utilization

roaring/roaring.go, roaring/roaring_internal_test.go
=> implement container.flipBitmap() to improve differenceRunBitmap()

input_definition_test.go
see https://github.com/golang/go/issues/8560
also gofmting happening
=> forgotten error check which fooled the compiler but not guru/rename

roaring/roaring.go, roaring/roaring_internal_test.go, roaring/roaring_test.go
Various fixes that were introduced during the SSB benchmarking project.
=> Roaring optimizations

fragment.go
=> update fragment.FieldSum to use roaring IntersectionCount()

docs/administration.md
This fixes the name of a section heading and an incorrect flag in example code.
=> Fix section heading name and incorrect flag

docs/api-reference.md, docs/data-model.md, docs/query-language.md
=> 740 bsi doc v2

webui/assets/main.js
This changes the sidebar link to the docs in the WebUI to point to the version of docs that match the version of Pilosa you are using.
=> Modify WebUI documentation link to open docs for the current version.

docs/query-language.md
=> make the Sum query argument order consistent with other queries.

CHANGELOG.md, docs/installation.md
This adds the changelog and installation instructions for Pilosa v0.7.0.
=> Release v0.7.0

docs/data-model.md, docs/query-language.md
Fixes #
remove quotes from SetFieldValue field argumentremove quotes from SetFieldValue field argument
=> remove quotes from SetFieldValue field argument

Dockerfile, Gopkg.lock
This updates the Go version in Dockerfile and the versions of the vendored dependencies (via `dep ensure -u`).
It passes all tests.
=> Update dependencies and Go version

CHANGELOG.md, docs/installation.md
=> Release v0.7.1

docs/api-reference.md, frame.go, handler.go, handler_test.go, holder.go, index.go, view.go
Adds an endpoint at `/recalculatecaches` for triggering cache refresh on demand.
Fixes #880 
=> Add Recalculate Caches Endpoint

README.md
Just fixes the client libraries anchor in the readme.
=> TRIVIAL: Fixes client libraries anchor in the README

docs/howtos.md
This PR adds TLS cluster how to.
Currently requires, so blocked by: https://github.com/pilosa/pilosa/pull/889 and possibly https://github.com/pilosa/pilosa/pull/892
The required binary may be compiled from source after merging those branches or downloading one of:
Linux amd64: https://storage.googleapis.com/pilosa/pilosa-tls-linux
MacOS: https://storage.googleapis.com/pilosa/pilosa-tls-macos
=> Added TLS cluster how to

webui/assets/main.js
Fixes #883, WIP because other frame options still need to be added.
=> Remove row and column labels in webUI

client.go, cluster.go, cmd/root_test.go, cmd/server_test.go, config.go, ctl/generate_config.go, ctl/server.go, docs/configuration.md, gossip/gossip.go, handler.go, handler_test.go, holder.go, index.go, input_definition.go, internal/private.pb.go, internal/private.proto, server.go, server/server.go
Add Schema to proto.
Update MaxSlices in proto to include both standard and inverse.
Update LocalStatus (shared in gossip) to include MaxSlices and Schema.
Encode InputDefinitions with Index.
TODO:
- make sure InputDefinitions are considered in LocalStatus merge.
- decide what to do about `/slices/max` endpoint. client.backup is using
it.
@raskle This compiles but the tests are failing. I'm just putting this here as a WIP so you can see what direction I'm thinking with the status/schema stuff.
=> Update status schema

client_test.go, cluster.go, cluster_test.go, executor_test.go, frame.go, holder.go, server.go, test/cluster.go, uri.go
Consolidate schema creation into Holder.ApplySchema.
Add view names to proto schema.
=> Add Cluster resize tests.

Gopkg.lock, config.go, ctl/server.go, diagnostics/diagnostics.go, diagnostics/diagnostics_test.go, docs/administration.md, docs/configuration.md, holder.go, server.go, server/server.go, stats.go, stats_test.go, statsd/statsd.go
Diagnostics Client implementation
=> Diagnostics

executor_test.go, handler.go, server.go
@raskle I ported your fix from #897 over to this branch.
=> 891 nodeid tags (from #897)

client_test.go, executor_test.go, uri.go
Fixes #
Fix test string format issues that are failing in the stricter CI checks on Master.
=> Fix test string format

cmd/server_test.go, config.go, ctl/generate_config.go, ctl/server.go, docs/configuration.md, server/server_test.go
Add documentation and tests for a few config options and remove unused `plugins.path` option.
Fixes #915 
=> Add flag documentation and tests, remove "plugins.path"

Makefile
This adds an alternative build process that cross-compiles Pilosa in a Docker container. This is helpful in the case that a Linux-based build environment is desired and will become the default build process for Linux release builds.
=> Add docker-build make target for repeatable Docker-based builds.

cache.go, diagnostics/diagnostics.go, server.go
Fixes a few typos in comments and output.
=> fix a few typos

docs/administration.md
This adds documentation on importing field values.
Fixes #924
=> Add documentation on importing field values. Fixes #924.

server/server_test.go
`TestMain_SendReceiveMessage` has several problems that are intermittently causing tests to fail. See issue #951 for details. This PR comments out this test until the issues can be addressed.
=> comment out test TestMain_SendReceiveMessage 

docs/administration.md
=> Format list properly

server/server_test.go
TestCountOpenFiles test is fragile in some environments due to unpredictable open file count. This simplifies it to only ensure the count is not 0.
=> Simplify TestCountOpenFiles

roaring/roaring.go, roaring/roaring_internal_test.go
corrected for the issue when a run ended in maxuint16
Fixes #939
=> fix overflow in differenceRunBitmap

.travis.yml
This re-enables CI on Go master (which has been failing), but allows the failure without breaking the build status.
See #956.
=> Re-enable CI on Go master, but allow failures. See #956.

CHANGELOG.md, Dockerfile, docs/installation.md
=> Release v0.7.2

CHANGELOG.md, Dockerfile, docs/installation.md
=> Release v0.8.0

CHANGELOG.md, diagnostics/diagnostics.go, diagnostics/diagnostics_test.go, docs/installation.md, server.go, server/server_test.go
Point release to fix Docker image and diagnostics version check.
=> Release v0.8.1

docs/client-libraries.md
=> TRIVIAL: updated Go client sample

docs/getting-started.md
=> language.txt -> languages.txt

Dockerfile
This binds Pilosa server to all interfaces by default when run in Docker.
Fixes #977
=> Bind the handler to all interfaces (0.0.0.0) in Dockerfile. Fixes #977.

cluster_test.go, fragment.go, frame.go, index.go, index_test.go, test/cluster.go
=> add SetFieldValue() method to TestCluster and use in tests

cluster.go, cluster_test.go, holder.go, holder_test.go, view.go, view_test.go
Add HolderCleaner and view.DeleteFragment to support post-resize cleanups
Add tests for view.DeleteFragment and HolderCleaner
=> Add HolderCleaner and view.DeleteFragment

CHANGELOG.md, docs/installation.md
This release includes the HTTP client bug fix from Todd. (#994)
=> Release v0.8.2

docs/input-definition.md
=> TRIVIAL: Fixes the import data section in the input definition docs

docs/configuration.md
=> Added single cluster config; implements #871

cluster.go, holder.go, server/server.go
converted to single http client method
=> adjust to single http client

roaring/roaring.go, roaring/roaring_internal_test.go
A user of Pilosa is seeing segfaults in container.unmap() and container.clone() (on the `copy()`) lines. Difficult to reproduce, but it seems possible that not clearing a fragment's in-memory Bitmap when closing the storage could potentially be causing this - see these lines in fragment.go: 
```
func (f *Fragment) closeStorage() error {
// Clear the storage bitmap so it doesn't access the closed mmap.
//f.storage = roaring.NewBitmap()
```
It's clear that if Bitmap.UnmarshalBinary is called when the bitmap already has containers that point to unmapped data, and the data that it is unmarshalling does not match the exact container types for the unmapped data, then the next time `unmap()` or `clone()` is called, disaster will strike.
What is unclear, is when or how UnmarshalBinary would be …
=> protect against accessing pointers to memory which was unmapped

roaring/roaring.go, roaring/roaring_internal_test.go
see #1000 - that was against v0.8, this is the same work into master
Fixes #
=> Unmapped mem master

cmd/import.go, docs/api-reference.md, docs/webui.md
Deprecates index time quantum and removes it from the docs and `pilosa import` command.
Fixes #978 
=> Deprecate index time quantum in the docs; resolves #978

docs/getting-started.md
=> remove frame options from getting started

roaring/roaring.go
Add proper error handing to write errors on roaring bitmap.WriteTo
Fixes #1011 
=> added error checking to WriteTo

roaring/roaring_test.go
Provided new benchmarks to evaluate container management data structures
=> added benchmark for various container usage patterns

Gopkg.lock, Gopkg.toml, diagnostics/diagnostics.go, server.go
Implements #988
Implements #989 
=> Adds CPU and mem info to the diagnostics payload. Implements #988, #989

server.go
Close HTTP handler gracefully.
Fixes #1018.
=> Close HTTP handler gracefully (Fixes #1018)

docs/tutorials.md
Adds a tutorial section to the docs that demonstrates a very basic use of BSI fields.
=> BSI tutorial

server.go
=> Added BSIFieldCount diagnostics; refactored schema diagnostics

docs/tutorials.md
Adds a simple tutorial for using row/column attributes.
Let me know if you think there's anything else that we should cover on this topic.
@codysoyland I took a pass at standardizing the Tutorial labels, but comment on this PR if you want something different.
=> basic row/col attribute tutorial

roaring/roaring.go
Replace linear search with binary search on runAdd
Fixes #954
=> added binary search to runAdd

gossip/gossip.go
Using `memberlist.DefaultLocalConfig` is not necessarily ideal for production environments. We have addressed this in the `cluster-resize` branch by supporting memberlist config options, but for the current version we just change to using `memberlist.DefaultWANConfig` instead.
=> change gossip config from DefaultLocalConfig to DefaultWANConfig

diagnostics/diagnostics.go, diagnostics/diagnostics_test.go
All other diagnostics metrics are capitalized, so I'm changing this to be consistent with the others.
=> Rename diagnostics metric "uptime" to "Uptime"

docs/tutorials.md
@codysoyland added suggestions to #1022 after it had been approved. This PR applies those suggestions.
=> apply comments in #1022

Gopkg.lock, Gopkg.toml, frame.go, holder.go, server.go, server/server_test.go
port of #1042 to master
Fixes #
=> Readlocks master

handler.go, handler_test.go
=> [Trivial] [Low priority] Makes /version endpoint semver-compatible

Gopkg.lock, gossip/gossip.go, test/pilosa.go, test/pilosa_test.go
Adds a helper function to create in-process pilosa clusters.
Fixes #1044 
=> add NewServerCluster(size int) method to pilosa/test

CHANGELOG.md, docs/installation.md
This fixes the Docker issue reported in #977.
Fixes #977 
Fixes #1060 
=> Release v0.8.5

server/server_test.go, test/pilosa.go
=> Uses NewServerCluster method in tests

README.md
Idea borrowed from https://github.com/google/metallb. Improvements to https://github.com/pilosa/pilosa/issues/1074 are welcome.
=> Link to usage question issue

docs/getting-started.md
=> Takes back frame options in getting started docs

bitmap_test.go, roaring/roaring.go, roaring/roaring_internal_test.go
There was a case where the Bitmap iterator logic could skip over a bit in a run
container if 1. the run container was not the first container in the bitmap, and
2. The first run in the run container had only one bit.
The bug was due to how the iterator was initialized with iterator.Seek(0) which
sets up the initial values of itr.i,j,k based on the type of the first
container. It was failing to set itr.k to -1 unless the first container was an
RLE container. itr.k is only used by RLE containers in the iterator, and must be
set to -1 when an RLE container is encountered. When Iterator.Next() encountered
the run container and itr.k was set to 0, it checked to see if itr.k <= run.last
- run.first, and if so it assumes that it was finished with the run and moved to
the next one. run.last - …
=> fix count/bitmap mismatch bug on master

CHANGELOG.md, Dockerfile, docs/installation.md
updates changelog, dockerfile and docs for v0.8.6
Fixes #
=> update CHANGELOG, docs and Dockerfile for v0.8.6

docs/api-reference.md, docs/getting-started.md, docs/query-language.md, docs/tutorials.md
Adds `request` and `response` tags to the docs for better formatting.
=> add request/response tags to the docs

handler.go
Existing code panics due to calling `err.Error()` on nil error. This replaces that call with a string literal.
=> Fix node id validation on set-coordinator

Gopkg.lock, handler_test.go, server.go
=> [TRIVIAL] 1092 context replacement

.travis.yml, Makefile
This builds pre-release binaries for all branches (not just master).
=> Make pre-release builds for all branches

.travis.yml, Makefile
Prerelease uploads broke on Travis CI because Travis doesn't check out branches like normal and the GOOS/GOARCH variables weren't set.
=> Cluster resize fix prerelease upload

docs/configuration.md
=> remove cluster type http from docs v0.8

Gopkg.lock, handler.go, handler_test.go
This PR adds query argument validation to all relevant handlers (taking query arguments).
Fixes #652 
=> Validate /fragment/nodes arguments. Fixes #652

cluster.go, handler.go, handler_test.go, server/cluster_test.go
Adds some validation around various `remove-node` options.
=> add validation around node-remove conditions

cluster.go, gossip/gossip.go, server/cluster_test.go, server/server.go
Addresses the issues mentioned by @jaffee in https://github.com/pilosa/pilosa/pull/904#pullrequestreview-96134856
=> replace swallowed error with log entry

gc.go, gcnotify/gcnotify.go, server.go, server/server.go
Creates a `GCNotify` interface to remove dependency from pilosa package.
Fixes #1095 
=> put GCNotify behind an interface

docs/administration.md, docs/query-language.md
Formatting fix, and add Xor to docs
=> Docs fixes

docs/client-libraries.md, docs/data-model.md, docs/getting-started.md
=> add warnings about sequential ids

cluster.go, holder_test.go
Add comments to exported methods.
Remove a commented-out debugging test.
=> add comments to exported methods. remove debugging test.

broadcast.go, docs/administration.md, docs/client-libraries.md, docs/data-model.md, docs/getting-started.md, docs/query-language.md, roaring/roaring.go, server/server.go, test/cluster.go
Removes the `Join` method from `StaticMemberSet`. This implementation of the interface is only meant for testing.
=> Cluster resize staticmemberset

cluster.go, server/cluster_test.go
This handles the case when replicas=1 but removing nodes that have data. This will:
1. Respond to HTTP request with error if that condition is met, and
2. Cancel the job and reset cluster state to NORMAL if that condition is met.
=> Proper error handling when attempting to remove node when there aren't enough replicas

ctl/import_test.go, executor.go, fragment_test.go, gossip/gossip.go, handler.go, roaring/roaring.go, roaring/roaring_test.go, statsd/statsd.go
=> Fix misspells in comments

gopsutil/systeminfo.go, gopsutil/systeminfo_test.go, security_manager.go, statik/doc.go
This adds the license text to files that are missing it.
For future reference, a command to find files that are missing it is:
```find . -name "*.go" ! -path "./vendor/*" | while read f; do head -1 $f | grep -v "^\/\/ Copyright 2017 Pilosa Corp" > /dev/null && echo $f; done```
=> Add license text headers

config.go, ctl/server.go, gossip/gossip.go
This PR removes the duplicated `Gossip` from the memberlist-related config options.
=> remove the Gossip stutter from memberlist-related config options

CHANGELOG.md
This brings the CHANGELOG on master up to date with the latest release.
=> Add CHANGELOG changes from v0.8 to master

CHANGELOG.md
This is a first draft of release notes for v0.9.
I applied the usual discretion of omitting trivial PRs and ones that don't considerably impact end users (tests, comment changes, doc typo fixes). I grouped many of the cluster-resize-specific PRs under the top item in "Added." The docs-specific changes are grouped under the bottom item in "Added." This release has a ton of great testing improvements, so I think I'll re-add those omitted PRs (as a grouping like docs/cluster-resize? or a section?).
=> Add unfinished release notes for v0.9

bitmap.go
This removes an unused cgo statement at the top of `bitmap.go` (previously used for popcount).
=> Remove unused cgo preamble

webui/assets/main.js
This fixes a few issues with WebUI after recent API changes:
- Version endpoint is now missing the preceding "v".
- Status endpoint has been modified and no longer contains schema info.
=> WebUI fixes for compatibility with API changes

.travis.yml, Makefile
This fixes an issue where all builds are performed in Docker (prerelease builds that run in CI cannot use Docker since it is not available).
=> Fix syntax on conditional check for docker-build config

api.go, cluster.go, executor.go, fragment.go, handler.go, handler_test.go, holder.go, pilosa.go, test/cluster.go
I still have more to do (none of the API methods should accept or return `internal.` structs), but I think this is enough to review. Please refer to the individual commit messages for more detailed descriptions of what's been done.
Fixes #
=> Handler api refactoring

docs/getting-started.md, docs/tutorials.md
Updated tutorials for the latest master.
=> Updated tutorials

handler.go, handler_test.go
=> [TRIVIAL] index param is required for /fragment/nodes

api.go
just fixing a small oopsy from the api/handler refactoring PR
Fixes #
=> use io.WriterTo instead of custom

cluster.go, config.go, config_test.go, ctl/generate_config_test.go, ctl/import_test.go, docs/configuration.md, fragment.go, server.go, server/server.go
these were occaisionally referenced elsewhere in the codebase - in all but one
case, there were workarounds that are actually better I think.
In the one case there wasn't I created a single top level DefaultConfig object
which is instantiated with all the default values and can be referred to if
necessary.
There was a bug in fragment.go with the way MaxWritesPerRequest was treated if
it was 0. Elsewhere, 0 meant no limit, but here, it would have caused a division
by 0.
Changed the default metrics provider from "nop" to "none", although "nop" will
still work. Previously, any value other than "statsd" or "expvar" was treated as
"nop", but I've changed this behavior to return an error if an invalid string is
provided. I think this is better behavior, because in the case that someone
bothered …
=> remove global defaults from config.go

roaring/roaring.go, roaring/roaring_helpers_test.go, roaring/roaring_internal_test.go
This PR changes `flipBitmap()` from being a method on the container to being a function which takes a container as an argument. This is more consistent with other container functions. Now there is a `flip()` function which calls `flip<container-type>()`.
Also adds `flip` to the container tests. I modified the `testOp` struct to take an interface instead of a function to allow for the different function signature of `flip`. This can be better, but until we need to handle more types in this test case, I'm going to leave it as is.
Fixes #850 
=> clean up flipBitmap and add tests

broadcast_test.go, client_test.go, cmd/server.go, cmd/server_test.go, ctl/common.go, ctl/server.go, diagnostics.go, gossip/gossip.go, handler.go, holder.go, holder_test.go, server.go, server/cluster_test.go, server/server.go, server/server_test.go, test/executor.go, test/pilosa.go, test/test.go
trying to separate internal an external concerns in pilosa.Server - it should
handle Cluster, Holder, etc. while pilosa/server handles things with external
deps - e.g. Logger, Stats, Handler, etc. Using functional options in
pilosa.Server now.
Fixes #
=> refactoring pilosa/server

docs/administration.md, docs/api-reference.md, docs/data-model.md, docs/glossary.md, docs/pdk.md, docs/query-language.md
I missed some references to row and column labels in the docs while working on #1180. This addresses that.
=> remove references to row and column labels from the docs

.travis.yml
Runs the test on 32bits too.
Fixes https://github.com/pilosa/general/issues/32
=> Run 32bits on CI

Dockerfile, Gopkg.lock, Makefile, NOTICE, cache.go, lru/lru.go
Vendor the lru package in `github.com/golang/groupcache/lru`
Fixes #1098 
=> vendor github.com/golang/groupcache/lru. rebuild Gopkg.lock

docs/administration.md
This covers some important changes for the Pilosa 0.9 release.
=> Add docs for upgrading Pilosa

holder.go
This renames the Node ID file from "ID" to ".id" to be consistent with our internal convention.
=> Rename ID file to ".id" for consistency with existing data files

api.go, cluster.go, cluster_test.go, server/cluster_test.go, test/pilosa.go, utils_test.go
Fixes some race conditions in the Cluster code. There may be more, but this seems to be helping the build to pass.
Fixes #
=> Cluster race conds

CHANGELOG.md, Dockerfile, docs/installation.md
=> Release v0.9.0

CHANGELOG.md
This updates the changelog with all remaining changes for the v0.9 release.
=> WIP: Update changelog for v0.9

client.go, client_test.go, ctl/bench.go, executor.go, fragment.go, server.go
See individual commit messages.
Fixes #
=> Fixup internal client

frame.go, index.go
`Import()` was creating a slice of nil values. This PR sends an empty slice unless one or more bits contain a timestamp value.
=> avoid creating a slice of nil timestamps on Import()

docs/query-language.md
Usage of `ClearBit` was incorrectly shown as `SetBit` in the documentation.
Fixes a minuscule documentation issue.
=> Correct usage of ClearBit in docs

client.go
=> Wrap errors in client.go

server/server.go, server/server_test.go
=> Wrap errors in server/

ctl/backup.go, ctl/bench.go, ctl/bench_test.go, ctl/check.go, ctl/check_test.go, ctl/common.go, ctl/export.go, ctl/import.go, ctl/inspect.go, ctl/restore.go
=> Wrap errors in ctl/*.go

cluster.go, cluster_internal_test.go
=> Wrap errors in cluster.go

handler.go
=> Wrap errors in handler

broadcast.go, diagnostics.go, gossip/gossip.go, server.go, uri.go
=> Wrap remaining errors in a few more files

boltdb/attrstore.go, holder_test.go
=> Wrap errors in attrstore

api.go, handler_test.go, server/server_test.go
=> Wrap errors in api

fragment.go, holder_test.go
=> Wrap errors in fragment

frame.go, handler_test.go, holder_test.go
=> Wrap errors in frame

holder.go, holder_test.go, index.go
=> Wrap errors index

client.go, docs/administration.md, docs/api-reference.md, handler.go, handler_test.go, server/cluster_test.go
=> Removes /id and /hosts endpoints. Adds local ID to /status

webui/index.html
Update the help menu in WebUI to match current PQL.
Fixes #1277.
=> Update help menu in WebUI. Fixes #1277.

ctl/bench.go
Fixes another missed `columnID`->`col`
=> Update PQL syntax in bench subcommand

CONTRIBUTING.md, cmd/import.go, cmd/root.go, docs/README.md, docs/administration.md, docs/api-reference.md, docs/client-libraries.md, docs/configuration.md, docs/data-model.md, docs/examples.md, docs/faq.md, docs/getting-started.md, docs/glossary.md, docs/installation.md, docs/introduction.md, docs/pdk.md, docs/query-language.md, docs/tutorials.md, docs/webui.md
This contains a bunch of docs fixes and additions, focusing on "docs landing pages", i.e., introduction, getting started, readme, and other pages explicitly linked from those. Fixes are focused on syntax (to ensure all code snippets in the docs run as expected) and wording (to remove outdated references, and to make every subsection as clear and self-contained as possible).
High level summary:
- Added a "relational analogy" section. We can expand this, but I wanted to get some basic feedback first.
- Ran every code snippet on the included pages, fixed syntax errors, displayed results in a "response" block (query-language, examples, client-libraries).
- Picked a consistent format for query-language sections. The query description comes before the "request" code block, which is now followed …
=> Assorted docs fixes

Makefile
Fix syntax error and add i386 enterprise build
=> Fix syntax error and add i386 enterprise build

Makefile
Fix syntax error and add i386 enterprise build
=> Fix syntax error and add i386 enterprise build (v0.10)

Makefile
Re-add unintentionally removed check-clean. Add ability to skip check-clean.
=> Re-add unintentionally removed check-clean

Makefile
Re-add unintentionally removed check-clean. Add ability to skip check-clean.
=> Re-add unintentionally removed check-clean (v0.10)

docs/tutorials.md
=> Added Docker cluster tutorial

Makefile
Fix syntax for multiple build tags, add boolean flag for RELEASE, improve boolean handling to support "0"
=> Makefile enterprise build fixes

Makefile
Fix syntax for multiple build tags, add boolean flag for RELEASE, improve boolean handling to support "0"
=> Makefile enterprise build fixes (v0.10)

handler.go
makes sure we're matching against unwrapped errors. created #1303 to add regression tests
=> use errors.Cause in handler so that we return correct status codes

server/cluster_test.go
This applies #1297 to the v0.10 branch.
=> adjust cluster state tests so they aren't so dependent upon a sleep (v0.10)

Makefile
Use lazy assignment for VERSION_ID so enterprise flag is set appropriately.
=> Use lazy assignment for VERSION_ID so enterprise flag is set appropriately

handler.go
=> wrap switch errs in errors.Cause in handler

docs/tutorials.md
=> Docker swarm tutorial

handler.go
This backports #1304 and #1309 to v0.10.
=> Backport #1304 and #1309 (errors.Cause) to v0.10

CHANGELOG.md, docs/installation.md
=> Release v0.10.1

docs/query-language.md
=> ClearBit doc fix

api.go, client.go, cmd/root_test.go, handler.go
=> More backup/restore stuff removal

.travis.yml
This should reduce the CI runtime quite a bit.
=> Exclude/remove CI matrix configurations to speed up CI process

executor.go, executor_test.go, fragment.go, fragment_test.go, frame.go, frame_test.go, test/cluster.go, utils_test.go, view.go
This is part two in a series of PRs working to rename `Frame` to `Field`. See #1351 for the previous step.
=> Rename SetFieldValue to SetValue

ctl/import.go, executor_test.go, fragment_test.go, frame_test.go
This PR should be the last instances of `field` or `Field` that are not either in docs, in comments, or part of a variable where it made sense just to leave it.
=> Field rename

cluster.go, executor.go, field.go, gossip/gossip.go, index.go, pilosa.go, pilosa_internal_test.go, pilosa_test.go, server.go, server/server_test.go, server_internal_test.go, server_test.go, stats.go, statsd/statsd.go, time.go, time_internal_test.go, view.go
This PR un-exports (or removes) quite a few top-level functions. Most are helper functions—used internally—which don't need to be exported.
=> un-export some top-level functions

api.go, cluster.go, fragment.go, handler.go, holder.go, holder_test.go, http/handler.go, server.go, server/server.go
This removes all net/http references from non-test code in the base package (except diagnostics), making the Handler pluggable.
=> Remove more net/http references

cluster.go, gossip/gossip.go, server.go, server/server.go, view.go
This makes some progress on #1247 . Still plenty to do, but this seemed like a good start without too many changes and all tests passing.
Fixes #
=> remove broadcaster methods from gossip- don't use sendAsync anywhere

cluster_internal_test.go, utils_internal_test.go
=> cleanup addnode unexport

diagnostics.go, server.go, server/server.go, test/pilosa.go
Server doesn't need a NewAttrStore func, and Holder doesn't need to be exported on Server any more.
Also pushing some other very straightforward unexports (totally automatic via gorename).
=> Server cleanup

cluster.go, executor.go, executor_test.go, fragment.go, http/client_test.go, http/handler_test.go, server/cluster_test.go, server/config.go, server/server_test.go, stats_test.go
Builds on new PQL PEG parser in #1382 to address #1318. More executor tests might be needed, possibly using #1378.
=> Update to new PQL syntax beyond the parser

enterprise/b/containers_btree.go, roaring/containers.go, roaring/roaring.go
=> backport fix for issue #1400

api.go
Remove redundant fields from API (a few remain due to test overrides)
=> Remove redundant fields from API

pql/pql.peg, pql/pql.peg.go, pql/pqlpeg_test.go
Add dashes to allowed characters on frame names.
Fixes #1414 
=> allow dashes in frame names

cluster.go, gossip/gossip.go, server/cluster_test.go, server/server.go, test/pilosa.go, utils_internal_test.go
I recommend looking at each commit separately.
partially addresses #1247 
=> Test runcluster simplify

api.go, broadcast.go, cluster.go, cluster_internal_test.go, event.go, fragment.go, server.go, utils_internal_test.go
=> remove some unused interfaces and implementations from broadcast.go

http/translator_test.go, mock/mock.go, translate.go
=> Fix a few data races

ctl/export_test.go, ctl/import_test.go, executor_test.go, http/client_test.go, http/translator_test.go, server/cluster_test.go, server/handler_test.go, server/server_test.go, server_test.go, stats_test.go, test/pilosa.go, test/pilosa_test.go
introduce Cluster type, improve naming
=> Enhance test utilities

api.go, test/handler.go
=> Remove API.Broadcaster

translate.go, translate_mapsize_386.go, translate_mapsize_all64bitsystems.go
=> define map size separately for 32 and 64 bit systems

executor_test.go
improved test coverage on time fields
=> more comprehensive time quantum tests

api.go, cluster.go, cluster_internal_test.go, executor.go, fragment.go, holder.go, server.go, utils_internal_test.go
=> unexport cluster (gorename)

api.go, executor.go, server.go
=> more unexports - executor, api fields

api.go, attr.go, broadcast.go, cluster.go, cluster_internal_test.go, executor.go, field.go, holder.go, index.go, server.go, translate.go, utils_internal_test.go, view.go
=> Even more unexport

api.go, cluster.go, cluster_internal_test.go, executor_test.go, field.go, field_internal_test.go, field_test.go, fragment_internal_test.go, holder.go, holder_internal_test.go, holder_test.go, server.go, test/holder.go, utils_internal_test.go
=> work on unexporting View stuff

cache.go, client.go, fragment.go, fragment_internal_test.go, iterator.go, iterator_test.go
=> Unexport cache stuff

api.go, cluster.go, cluster_internal_test.go, executor.go, executor_test.go, field.go, field_internal_test.go, fragment_internal_test.go, holder.go, holder_internal_test.go, test/holder.go, view.go, view_internal_test.go
=> Unexport view stuff

cluster.go, diagnostics.go, executor.go, field_internal_test.go, holder.go, holder_internal_test.go, index.go, server.go, test/pilosa.go
more unexports - straight gorename
=> Unexport index stuff

pql/pql.peg, pql/pql.peg.go, pql/pqlpeg_test.go
=> support newlines in more places

api.go, apimethod_string.go, cluster.go, field.go, row.go, time.go, time_internal_test.go, uri.go, uri_internal_test.go
Dead code identified by @codysoyland 's unexport script.
=> remove some dead code highlighed by the unexport script

api.go, field.go, holder.go, http/handler.go, index.go
this is on top of your last pull request @travisturner  and fixes a hack I made in api/gossip
Fixes #
=> Remove api holder

http/handler.go
This maybe a bit better than before, but I think a more holistic approach is needed where each pilosa error either by it's type or by some kind of status method can signal what status should be responded with in the handler. Otherwise there is unwieldy error handling code in every handler, and it's quite brittle since any new error value returned might not be caught.
In any case, handlePostQuery won't return an internalServerError - right now we're just always returning "bad request" if we get an error. I don't know if this is necessarily correct, but for queries there are a lot of possible errors and most of them do boil down to a client error.
sort of addresses #1126
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything …
=> handle errors a bit better in handlePostQuery

field.go, index.go
Remove `Index.MarshalJSON()` and `Field.MarshalJSON`
=> remove index and field MarshalJSON

api.go, gossip/gossip.go
Fixes a hack I made when api.Schema was returning []*Index and not []*IndexInfo
I submitted a different PR for this earlier, but forgot to actually include the change.
=> remove Holder from API

ctl/common.go, ctl/export.go, ctl/import.go, encoding/proto/proto.go, enterprise/b/btree.go, enterprise/b/containers_btree.go, gcnotify/gcnotify.go, gopsutil/systeminfo.go, gossip/gossip.go, http/client.go, http/error.go, http/handler.go, http/translator.go, inmem/translator.go, lru/lru.go, pql/ast.go, pql/parser.go, roaring/containers.go, roaring/roaring.go, roaring/roaring_helpers_test.go, roaring/roaring_internal_test.go, server/default.go, server/release.go, server/server.go, statsd/statsd.go, test/field.go, test/index.go, test/logger.go, test/pilosa.go
This branch is the result of a script that unexports everything possible while still passing tests.
This PR replaces #1455 and #1460.
=> Unexport all possible items

CHANGELOG.md
=> Add more changelog updates

Dockerfile, docs/installation.md
=> Update docs and Dockerfile for 1.0.0 release

pql/pql.peg, pql/pql.peg.go, pql/pqlpeg_test.go
Updates the `col` rule support single quoted column keys (which matches the `item` rule).
=> peg: Allow single quoted key 'col'

translate_mapsize_386.go
=> Unexport DefaultMapSize on 32-bit

Makefile
=> Use `dep ensure -vendor-only` for build repeatability

docs/console.md
=> Rename WebUI to Console, update installation instructions.

CHANGELOG.md, Makefile, docs/console.md, docs/installation.md, encoding/proto/proto.go, executor_test.go, gossip/gossip.go, http/handler.go, server.go, server/server.go, test/pilosa.go, time.go, time_internal_test.go
=> Release 1.0.1

docs/api-reference.md, docs/data-model.md, docs/getting-started.md, docs/glossary.md, docs/introduction.md, docs/tutorials.md
This PR adjusts some documentation to improve the `field` and field `type` descriptions.
It also fixes a few issues with examples.
Fixes #1481
=> another pass through the docs adjusting for fields and field types

executor.go, fragment.go, row.go
This method was previously unexported with an automatic unexporting tool. It
seems to be something that should be exported.
=> Re-export Row.Intersect

docs/query-language.md
=> Remove errant char at top of query language doc

docs/query-language.md
=> Backport #1503

.travis.yml, Makefile
Creates the following 3 stages:
1. add cached vendor directory, run metalinter
2. tests with env matrix
3. prerelease compilation/upload
Fixes #1299, #1288, and #1497 
=> Add TravisCI staged builds

Makefile, ctl/import_test.go, ctl/inspect_test.go, fragment.go, roaring/roaring_internal_test.go, test/pilosa.go, test/pilosa_test.go
=> Fix linter issues: ineffassign

Makefile, boltdb/attrstore.go, enterprise/b/btree.go, enterprise/b/containers_btree.go, field.go, fragment.go, http/handler.go, lru/lru.go, roaring/roaring.go
=> Fix linter issues: nakedret

cluster.go, utils_internal_test.go
Still more to do on this, but the last commit that fixes the test stuff should make it easier to do the rest.
fixes #1370 
=> 1370 cluster locking

Makefile, cluster.go, ctl/import.go, enterprise/b/containers_btree.go, field.go, server.go
=> Fix linter issues: maligned

translate_test.go
implements locked Reader method on test.TranslateFile. This race condition is
only present in tests, and is due to a replica referring directly to a primary
instead of through an http.TranslateStore as it would in production. This patch
requires the replica to obtain a lock while accessing the primary, and requires
test.Reopen to obtain a lock when swapping out the pilosa.TranslateStore.
I was able to reproduce the race by running: "go test
-run=TestTranslateFile_PrimaryTranslateStore -race -count=10", and could not
reproduce it after this patch.
Somewhat unrelated, I came across a "fatal error: fault" triggered by trying to
print an open pilosa.TranslateFile. This seems to be related to the mmapped
".data" field. I wrote the test to document the issue, but I don't think it's
easily …
=> fix race cond in translate_test

Makefile, ctl/import.go, gossip/gossip.go, http/error.go, index.go, server/server_test.go
=> Fix linter issues: vet

http/translator_test.go, server/handler_test.go
Add more time to sleep in translator tests due to CI failures
=> Add more time to sleep in translator tests due to CI failures

http/translator_test.go
Backport #1571 from master to v1.0
=> Backport #1571

CHANGELOG.md, docs/installation.md
=> Release v1.0.2

Makefile, attr_test.go, boltdb/attrstore.go, cluster.go, cmd/check.go, cmd/config.go, cmd/export.go, cmd/generate_config.go, cmd/import.go, cmd/inspect.go, ctl/import.go, field.go, fragment.go, holder_internal_test.go, http/client_test.go, http/handler.go, http/translator_test.go, lru/lru.go, pql/ast.go, pql/pqlpeg_test.go, roaring/roaring_internal_test.go, server/config_test.go, server/server_test.go, test/holder.go, test/pilosa.go, translate.go, translate_test.go, view.go
=> Fix linter issues: megacheck (unused/staticcheck/gosimple)

Makefile, boltdb/attrstore.go, cache.go, field.go, server/server.go, translate.go
=> Fix linter issues: unconvert

Gopkg.lock, Gopkg.toml, api.go, cluster.go, server/server_test.go, test/pilosa.go
Fixes #1249
Please see individual commits for a description of the goings-on.
=> Add DEGRADED cluster state and handle gossip NodeLeave events correctly

api.go, client.go, cmd/import.go, ctl/import.go, ctl/import_test.go, http/client.go, http/client_test.go, http/handler.go, test/pilosa.go
This is another pass at #1557. Now that #1578 has been addressed, it's safe to use this code. The commit https://github.com/pilosa/pilosa/commit/fd96d3a02ef2285aedad638bdfac50470a27a64c adds the logic to determine which node contains the writable translate file (i.e. the coordinator).
=> Support keys on import CLI

api.go, http/client_test.go
This PR adds key translation to the `exportCSV` function.
Fixes #1580
=> add key translation to exports

.circleci/config.yml, Makefile
Trying out CircleCI and it seems a lot faster and easier to configure than TravisCI. I think we should switch over.
=> Add CircleCI

CHANGELOG.md, docs/installation.md
=> Release v1.1.0

cmd/check.go, cmd/config.go, cmd/export.go, cmd/generate_config.go, cmd/inspect.go
=> Use passed stdin, stdout and stderr in the cmd package. Fixes #1538

test/pilosa.go
This PR replaces `*testing.T` in the test package with the interface `testing.TB` so that the test helpers can be used in benchmarks.
=> replace *testing.T with interface testing.TB

test/pilosa.go
the buffers were unused internally and external users had no access to them.
Those wishing to read the logs of the cluster in tests may replace stdout/stderr
with buffers on the Command struct.
The race occurred when a node was stopped and then started again. some
memberlist goroutines might not be completely cleaned up by the time the node
restarted, and then two loggers were using the same output buffer.
Fixes #1609 
=> remove unused log buffers from test cluster, fixes race

roaring/roaring.go
Trivial fix of 2 comments in roaring bitmaps code.
=> Trivial comment fix

fragment.go, fragment_internal_test.go
This PR ensures that data imported into a `mutex` field is handled correctly (i.e. only allow one row per column).
Fixes #1652 
(This PR addresses the `mutex` portion of #1652. The `bool` will be handled separately along with the PR that introduces `bool` fields.)
=> ensure mutex imports unset previous columns

ctl/import_test.go, docs/administration.md, docs/api-reference.md, docs/data-model.md, docs/glossary.md, docs/tutorials.md, executor.go, executor_test.go, field.go, fragment.go, fragment_internal_test.go, http/handler.go, pql/ast.go, view.go
This PR adds field type `bool`.
Fixes #1498 
=> add support for Bool fields

cache.go, docs/query-language.md, executor.go, executor_test.go, fragment.go, fragment_internal_test.go, pql/pql.peg, pql/pql.peg.go
This PR implements `ClearRow()`.
Fixes #1240 
TODO:
=> implement ClearRow() query

.circleci/config.yml
This allows go-pilosa and other client integration tests to run against Pilosa master.
=> Add CircleCI step to generate Docker image and push to Docker hub

http/handler.go, http/handler_internal_test.go, index.go
=> Index trackExistence is true by default Fixes #1637

executor_test.go
Fixes #1681 
Legend:
* `OK`: done
* `--`: N/A
* blank: not done
Call           | RowID / ColumnID | RowID / ColumnKey | RowKey / ColumnID | RowKey / ColumnKey
---------------|:----------------:|:-----------------:|:-----------------:|:-----------------:
Set            | OK               | OK                | OK                | OK
SetRowAttrs    | OK               | --                | OK                | --
SetColumnAttrs | OK               | --                | OK                | --
Clear          | OK               | OK                | OK                | OK
Row            | OK               | OK                | OK                | OK
Union          | OK               | OK                | OK                | OK
Intersect      | OK               | OK                | OK …
=> Adds missing rowID/Key columnID/Key tests

docs/api-reference.md
=> Updated API docs

docs/api-reference.md, docs/getting-started.md, docs/query-language.md
This adds pointers to client import documentation in a few places to make it more visible. We've had several users trying to use PQL to ingest large amounts of data with sad results.
Fixes #
=> add more import docs

executor.go, executor_test.go, fragment.go, fragment_internal_test.go, pql/pql.peg, pql/pql.peg.go, roaring/roaring.go, row.go
Adds a `TopXor` function which applies `XOR` to a source row and all rows in the cache, and returns the top N row counts ascending.
Not implemented here are performance enhancements such as:
roaring.xorCount
pairHeap threshold in `fragment.topXor()`
=> adds a TopXor() function similar to TopN

enterprise/b/btree.go, enterprise/b/containers_btree.go
enterprise/b: Ensure 64-bit range for btree keys.
The cmp() function used to compare btree keys was using the
trick of comparing unsigned values by coercing the result
of subtraction to a signed type. This is fine as long as
the range of differences never actually exceeds the limits
of the signed type. For instance, with int64, as long as
the magnitude of the difference is under 2^63 or so, it
works reasonably well.
Plain int, however, can be a 32-bit type, at which point
the magnitude of difference needed to break it is only
2^31 or so.
Subtraction and type conversion is enough cheaper than
branches that this is worth preserving, but it's worth
preserving by switching to an explicit int64 for the
operation and return type. This will not actually affect
performance except for people using …
=> Ensure btree comparison doesn't fail for smallish N

api.go, api_test.go, http/client.go, http/handler.go
This PR forwards translated import requests to the correct shard based on `columnID` provided or translated `columnKey` (see bug description in #1715).
Fixes #1715 
=> forward imports to non-coordinator shards

docs/data-model.md, docs/glossary.md
Fixes broken SVG images on the data model page. Depends on https://github.com/pilosa/www/pull/248
=> Minor docs updates

pql/pql.peg.go
Regenerate peg file after running `go get -u github.com/pointlander/peg`
=> upgrade peg at: github.com/pointlander/peg

api.go, fragment.go, roaring/roaring.go
=> Prevent panic in Bitmap.UnmarshalBinary when there is no data

api.go, cache.go, cluster.go, diagnostics.go, field.go, fragment.go, gossip/gossip.go, holder.go, http/handler.go, index.go, logger/logger.go, roaring/containers.go, roaring/roaring.go, roaring/roaring_internal_test.go, roaring/roaring_nop_stats.go, roaring/roaring_stats.go, server.go, server/server.go, stats/stats.go, stats/stats_test.go, statsd/statsd.go, translate.go, view.go
I was wondering how often particular things happen. When we're loading data, how often do we end up inserting data into the middle of an array, rather than appending it at the end? I have no idea. What if we tracked some of that? So, this branch provides a mechanism for tracking things like that. It's not a very fancy or powerful mechanism, but it should have zero runtime cost when not being used.
It's not currently actually added to the documentation, because there's no mention of the /debug/vars functionality right now. It might not be a bad idea to document it, if planning to use things like this, or just in general since it might be useful for users to know about it.
Note that the new code is controlled by a build tag.
There's also an unrelated and uncompiled test case which probably …
=> add some stat tracking to roaring/ implementation.

api.go, cluster.go, fragment.go, holder.go, server.go, server/server.go, translate.go
cleans up logging to start with lowercase in most cases (no pun intended).
uses syscall.Dup2 to write everything that's going to stderr to the configured log file (if any) instead. A little unsure of what the implications of this are in tests, but I it seems to be OK. I have one test failing with make docker-test, but it seems to fail regardless.
Fixes #1747 (at least mostly)
=> Logging cleanup

cluster.go, executor.go, holder.go, server.go
merge after #1746 
Fixes some races I found while working on the above.
=> More races

Gopkg.lock, api.go, attr.go, cluster.go, cmd/server.go, ctl/server.go, docs/configuration.md, executor.go, fragment.go, holder.go, http/client.go, http/handler.go, pilosa_internal_test.go, server.go, server/config.go, server/server.go, tracing/opentracing/opentracing.go, tracing/tracing.go
This pull request adds distributed tracing throughout the request paths in `API`, `Executor`, `Holder`, `Fragment`, and the `InternalClient`. It also implements HTTP header injection to pass tracing identifiers between nodes.
The tracing uses the production settings suggested by Jaeger by default. Two additional flags have been added to allow control over the sampler:
```
--tracing.sampler-type
--tracing.sampler-param
```
For testing/dev, you can have all spans reported by using these settings:
```sh
pilosa server --tracing.sampler-type const --tracing.sampler-param 1
```
=> Add distributed tracing.

executor.go, executor_test.go, pql/ast.go, pql/pql.peg, pql/pql.peg.go, pql/pqlpeg_test.go
This pull request adds the ability to specify a row call as the first argument to `GroupBy()` and apply that as a filter to the first level `GroupBy()` results.
Fixes #1726
=> Add GroupBy() Filter

holder_test.go
Copy/Paste mistake when updating the test. Now the test will actually fail without the fix.
=> fixed a mistake in the test from PR 1780

executor.go, pilosa.go
This commit periodicially checks if the context has been cancelled
or if a deadline has been reached. If so, it returns a query-related
error message depending on the cause.
Fixes #1745
=> Cancel queries on Context.Done()

Makefile
we did this in some other repos - not sure how we forgot PILOSA
=> add Gopkg.lock as a dependency for vendor target

CHANGELOG.md, Dockerfile, docs/installation.md
Changelog and updates for 1.2.0
=> Release v1.2.0

docs/query-language.md, executor.go, executor_test.go, pql/ast.go
Add docs for Group By and fix field crash issue. I may try to add Todd's request performance enhancement to this, but it is ready for review as is.
Fixes #1800 and #1801 
=> Group by fixes

api_test.go, docs/administration.md, docs/data-model.md, docs/glossary.md, docs/query-language.md, docs/tutorials.md, executor.go, executor_test.go, http/client_test.go, pql/ast.go, pql/pql.peg, pql/pql.peg.go, pql/pqlpeg_test.go
This commit refactors the `Range()` call and merges its functionality into the `Row()` call.
Fixes #1757
=> Merge Range() into Row() call.

.circleci/config.yml
=> add verbose flag to circle ci race test to help debug timeout

pql/pqlpeg_test.go
It seems that #1804 fixed the bug reported in #1816, so I'm just adding my test case here to make sure it's covered.
Fixes #1816
=> add a test for groupby filter with RangeLTLT

Makefile, docs/query-language.md, executor.go, executor_internal_test.go, executor_test.go, pql/pql.peg, pql/pql.peg.go, server/server_test.go
=> Fixes #1805. Fixes Store call error messages

cluster.go, ctl/import.go, diagnostics.go, diagnostics_internal_test.go, executor.go, fragment.go, gossip/gossip.go, http/handler.go, http/handler_internal_test.go, lru/lru.go, pql/ast.go, roaring/roaring.go, roaring/roaring_internal_test.go, server.go, server/cluster_test.go
fixes all the stuff reported by staticcheck and one errant logging statement
Fixes #
=> Staticcheck fixes (lint)

executor.go, gossip/gossip.go, server/server.go
This is... ugly, but it's less wrong than it used to be and shouldn't break anything. See new comments for more color.
This fixes an issue that was brought up in the comments of https://github.com/pilosa/pilosa/issues/1687
=> pass loggers around properly in gossip

translate.go
Depending on where in the replicate() loop you are when a
store is closed or reassigned, it's possible for it to deadlock.
The deadlock would be that replicate has just successfully read an
entry from your PrimaryTranslateStore.Reader, when a new
PrimaryTranslateStore event happens. Then handlePrimaryTranslateStore
grabs the mutex, signals that the replication handler should
close, and waits for the replication handler to close. Meanwhile,
the replicate() loop tries to grab the mutex... and deadlocks.
Solution: Make the replicate() loop part that needs the mutex
a goroutine that signals on a channel, so we can put it in a select
along with checking for the replicationClosing signal (or the
context terminating). If one of those happens, replicate()
terminates, allowing monitorReplication() …
=> prevent deadlock in replication logic on reopening a store

cluster_internal_test.go, executor_internal_test.go, executor_test.go, field_internal_test.go, fragment_internal_test.go, holder_internal_test.go, index_internal_test.go, server_internal_test.go, translate_test.go, utils_internal_test.go, view_internal_test.go
This is to allows the directory to be set to where a particular disk is mounted
during benchmarking.
=> make sure more tests and benchmarks can have their temp dir set by flag

roaring/roaring.go, roaring/roaring_test.go
=> added convenience function to efficiently calculate size of a roaring bitmap in bytes

docs/configuration.md
Cluster config referred to seed but the server now expects seeds
Fixes #
=> Replaced seed with seeds

docs/installation.md
Updated Docker and Windows sections in the docs.
=> Updated Docker and Windows sections in the docs

docs/query-language.md
=> add Group By heading to query language docs

view.go, view_internal_test.go
Revised this based on re-reading the code and trying to test it. It turns out that the reuse of old items in the fragments map is probably harmless, but there was an actual underlying race condition that could result in trying to reopen a fragment immediately after creating it, rather than using the just-opened fragment.
=> avoid probable race when creating fragments

fragment_internal_test.go, roaring/roaring.go
=> [fix] make sure to unmap containers before modifying

holder.go, index.go, server/handler_test.go
=> Adds shardWidth to index info in schema

ctl/server.go
Not sure how this was this wrong for this long. Unless I'm missing something...
Fixes #
=> [fix] improve help strings for metrics options

docs/configuration.md
Forgot to document the new option.
Fixes #
=> add config docs for max-map-count

cluster.go, field.go, holder.go, index.go, server.go, server_internal_test.go, view.go
This is an update of #1855 with a (kind of janky) test. I tried to make the test a bit more useful, but it's pretty difficult to set up the whole cluster and still be able to introspect it.
Fixes #1808 
=> Validate shard

.circleci/config.yml
=> Add Go 1.12 to CircleCI

fragment.go, fragment_internal_test.go
=> test concurrent value imports, fix race

docs/configuration.md, server/config.go
Sorry to inundate you with PRs @seebs, but since you're already familiar with these changes, I think this will be quick.
=> increase default max map and file counts [no changelog]

go.mod, go.sum
=> Add missing deps to go.mod/sum

executor_test.go, pql/pql.peg, pql/pql.peg.go, pql/pqlpeg_test.go
Allow old-style Range query.
Fixes #1843 
=> add parser rule to catch old-style Range query

docs/examples.md
=> Updated examples section

handler.go, server/handler_test.go
Return empty result set when query empty
Fixes #1840
=> Return empty result set when query empty. Fixes #1840

.github/PULL_REQUEST_TEMPLATE.md
This adds a few steps to the PR template to ensure we have good metadata for generating a changelog.
=> Add changelog steps to PR template

go.mod, go.sum
=> update to latest memberlist fork with race fixes

CHANGELOG.md, Dockerfile, docs/installation.md
=> Release v1.3.0

api.go, client.go, cluster.go, diagnostics.go, event.go, executor.go, field.go, fragment.go, fragment_internal_test.go, gc.go, handler.go, pilosa.go, row.go, server.go, translate.go, uri.go
This PR addresses most of the linter warnings raised in VS-Code.
=> fix some lint warnings raised in VS-Code

api.go, docs/api-reference.md, http/handler.go, server/handler_test.go
New API warning: this adds ApplySchema to pilosa.API and allows
POSTing to the /schema endpoint
Fixes #1955 
=> add ability to post schema using holder.applySchema

field.go, fragment.go, index.go, view.go
This PR adds more `Debugf()` statements in the `holder.Open()` process to hopefully help us get more insight into #1948.
=> Add more Debugf() statements to the holder open process

field.go, holder.go, index.go, server.go, server_internal_test.go, view.go
Backport #1951 from master to v1.3
=> Backport #1951

CHANGELOG.md, docs/installation.md
=> Release v1.3.1

api.go, field.go, fragment.go, fragment_internal_test.go, go.mod, go.sum, http/handler.go
There's lots more to do in this vein, but I've found this to be pretty interesting so far.
The way I've been testing this is in the infrastructure repo `terraform/examples`, I'll follow the instructions to create an taxi example and provision it like so:
```
make provision ANSIBLE_ARGS="-e tools_repo=https://github.com/jaffee/tools -e tools_version=imagine-tweaks -e tracing_sampler_type=const -e tracing_sampler_param=1 -e pilosa_repo=https://github.com/jaffee/pilosa -e pilosa_version=extra-tracing -e pilosa_long_query_time=1ns"
```
Then you can `make ssh-agent` and run something like 
```
cd go/src/github.com/pilosa/tools/imagine/
imagine -g -o 10.0.100.63 -s -t -v update samples/sports.toml
```
You should at this point be able to visit http://localhost:16686/ in your browser and see the …
=> Extra tracing

CONTRIBUTING.md
we can probably remove GOPATH too, but I'll save that for another day.
For now, we make it so that the obvious thing (cloning the official
repo) works as a normal part of the contribution process.
Fixes #
=> simplify contributing instructions by removing weird upstream thing

api.go, executor.go, executor_test.go, go.sum
=> Fix filter calls in GroupBy not being translated

executor.go, executor_test.go
This pull request improves field not found, integer field, and cache errors for the `TopN()` command.
Fixes #1942
=> Improve TopN() errors

api.go, field.go, http/handler.go, server/handler_test.go
=> 1977 fix int field min max

fragment_internal_test.go, roaring/roaring.go
also fix tests to use correct flags for BSI fields
Fixes #1985 
=> fixed swapped order of flags and file version bytes on unmarshal

fragment_internal_test.go, roaring/container_stash.go, roaring/roaring.go
Two bugs introduced by the rowcache work need to be fixed soonest.
=> Rowcache fix

go.mod, http/handler.go, prometheus/prometheus.go, prometheus/prometheus_test.go
- Refactor http stats collector as middleware
- Send path template instead of full url to reduce number of unique tags
- Send http method
- Return immediately after error conditions
- Use seconds instead of ms
- Add tests
=> Add Prometheus tests, refactor http stats as middleware, minor fixes

api.go, field.go, index.go, stats/stats_test.go, view.go
=> Remove extraneous stat tags to improve prometheus performance

Dockerfile
=> Update Alpine to 3.9.4 in Dockerfile

Dockerfile
Backport #2001 from master to v1.2
=> Backport #2001

cluster.go
=> more info if nodeleave confirmation queries fail

roaring/roaring.go, roaring/roaring_internal_test.go, roaring/roaring_test.go
This PR fixes various bugs in Roaring related to iteration through containers. The individual fixes are explained in the comments for the commit.
Fixes #2015 
=> Fix various container iteration bugs in Roaring

executor.go
=> Fixes #2009

docs/administration.md
Fixed the commit history from Pull Request #2043 
=> Updated Open File Limit in Administration Doc

docs/pdk.md
Fixed the commit history from Pull Request #2044 
=> Updated PDK

executor.go, executor_test.go, row.go
Use UnionInPlace when computing time rows which involve multiple views. Decreases memory allocation immensely.
=> Uip time only

docs/configuration.md, docs/query-language.md
=> Minor formatting and typo fixes

docs/glossary.md
=> Add Groupby and Rows to glossary, fix small issues

docs/query-language.md
=> Minor fixes to query language docs

.circleci/config.yml, go.mod, roaring/unmarshal_binary.go
=> Update CirleCI build with Go 1.13 and run enterprise tests

CHANGELOG.md, Dockerfile, docs/administration.md, docs/installation.md
=> Release v1.4.0

server.go, server/server_test.go
Test confirms race condition+simple fix using locked method rather than unprotected method.
Fixes #2066 
=> 2066 create field race

cmd/export.go, cmd/import.go, ctl/common.go, ctl/server.go, docs/configuration.md, docs/tutorials.md, http/translator.go, server/config.go, server/server.go
This fully enables TLS Mutual Authentication by verifying client certificates. Also updated docs to demonstrate this feature using certstrap.
=> Add support for TLS client certificate verification and custom CA

fragment.go
We're getting panics from a nil rowCache in some cases, and
it doesn't seem like this makes sense -- we shouldn't be
able to get out of openStorage without the rowCache being
initialized, without getting an error that prevents startup.
But we did, so let's just be a bit more careful. Also,
because it's a cheap check, we'll initialize the rowCache if
we somehow get to unprotectedRow without it being
initialized. Even though that shouldn't ever happen.
=> ensure row cache gets initialized in openStorage

field_internal_test.go
This PR adds a test for the bug fix in #2084
=> Add a test for pilosa/#2084

roaring/roaring.go, roaring/unmarshal_binary.go
We only have 4 bytes for offsets, but what if a file is
over 4GB? Someone came to us with a file with 265 *million* containers,
in a single fragment, which means that over 3GB of their 4.7GB file
is actually just the container headers alone. But we can't easily make
the offsets larger, or change the file format.
So we don't. We just track how many 4GB hunks of the file we've
been through and bump that every time the 32-bit offset wraps. And this
appears to... just work.
This is fixed for both the roaring iterator and the old unmarshalBinary
logic. The logic to handle this will work on 32-bit hosts in the sense
that it will correctly error out for excessively large file sizes or
container counts, but it doesn't actually handle the large files since
it can't.
(Backport from Molecula work.)
=> Handle file sizes over 4GB

api.go, api_test.go, cluster.go, executor.go, holder.go, http/client.go, index.go, pilosa.go, server/handler_test.go, test/holder.go
Make `not found index/field` error more verbose (contains name)
=> Make not found error more verbose (add name)

docs/getting-started.md
Fixes pilosa/getting-started#20
=> fix languages.txt link

field.go, fragment.go, fragment_internal_test.go, http/client_test.go
This is a back-port of #2084 to the `v1.4` branch.
=> Backport pr2084

CHANGELOG.md, Dockerfile, docs/installation.md
Update docs and changelog for v1.4.1
=> update changelog and docs for v1.4.1

docs/tutorials.md
Updates documentation relevant to https://github.com/pilosa/pilosa/issues/2129
=> Remove WSL references

README.md
=> Add slack link to readme

Makefile, shardwidth/16.go, shardwidth/17.go, shardwidth/18.go, shardwidth/19.go, shardwidth/20.go, shardwidth/21.go, shardwidth/22.go, shardwidth/23.go, shardwidth/24.go, shardwidth/25.go, shardwidth/26.go, shardwidth/27.go, shardwidth/28.go, shardwidth/29.go, shardwidth/30.go, shardwidth/31.go, shardwidth/32.go, shardwidth/helper.go
- removes build time constant in favor of single constant with relevant godoc and warnings
- removes code for build time config from makefile
closes #2184
=> feat: updates shardwidth.Exponent to single constant

README.md
This PR addresses some broken links pointing to docs in the README file
=> updated links in readme to point to latest pages in docs

sql3/planner/opbulkinsert.go
This PR handles introduces implicit type conversion from a float type in NDJSON to a single member stringset.
=> handle float --> stringset implicit map conversion in bulk insert

sql3/planner/planoptimizer.go
This PR modifies the optimizer to only turn a group by query table scan into a PQL group by if it is a direct child of the group by.
Previously, we had a case where if the child of the group by was a filter that had the table scan as a child, this resulted in the filter operator being removed from graph.
=> Optimizer fixes for Group By queries

sql3/planner/expression.go, sql3/planner/expressionanalyzercall.go, sql3/planner/inbuiltfunctionsstring.go, sql3/test/defs/defs_string_functions.go
SQL string function CharIndex to identify the position of the substring in the input string. Position starts at 0
=> Fb-1816 : CharIndex str func

api.go, cli/buffer.go, cli/cli.go, cli/cli_test.go, cli/fbcloud/client.go, cli/meta.go, cli/parts.go, cli/queryer.go, cli/splitter.go, cli/splitter_test.go, cli/workingdir.go, cli/writer.go, cli/writer_test.go, cmd/cli.go, dax/controller/schemar/boltdb/schemar.go, dax/queryer/client/client.go, dax/queryer/http/handler.go, dax/queryer/queryer.go, dax/test/dax/dax_test.go, sql3/planner/opalterdatabase.go
I'm putting this here in case anyone wants to try it out, but I'm leaving it in DRAFT until I sort out the DATABASE-specific stuff between cloud/on-prem.
=> CLI: make it more like psql

internal_client.go
=> use primary as source for FieldTranslate backup data

ctl/backup_tar.go, ctl/restore_tar.go, executor_test.go
=> Manual buffer management in restore-tar

task/pool.go, task/pool_test.go
When we close a task pool, we use a condition variable to wait for workers to exit, if any workers are still running. The workers, in turn, use the condition variable to notify that they've exited. Unfortunately, the workers aren't using the lock (the rationale was that it's all atomic ops so they don't need to), which means that it's possible to have the following sequence:
Close(): obtain current live count
worker: decrement live count
worker: send broadcast to condition variable
Close(): wait on condition variable
To resolve this, we make the worker update also request the lock.
We add a simple reproducer for this. Note that simple doesn't mean it fires completely reliably; on my laptop, the test causes a test timeout about 60% of the time without the fix. If you add a short delay …
=> task pool: avoid race condition on shutdown/close

dax/test/dax/dax_test.go, sql3/planner/executionplanner.go
Implemented "new" SQL tests now that CodedErrors are passed by HTTP
=> SQL tests now that CodedErrors are across HTTP

arrow.go, sql3/planner/opbulkinsert.go, sql3/sql_complex_test.go, translate_boltdb.go, wire_response.go
uses json.Decoder to allow for large integer values in ndjson format in bulk import
=>  fb-1915 Support large id's in NDJSON

ctl/backup.go, ctl/backup_tar.go, dax/controller/client/client.go, dax/queryer/client/client.go, dax/queryer/translator.go, dax/test/dax/dax_test.go, idk/serverless/importer.go, index_test.go
This turns out to be two interacting weird edge case bugs, where one bug was actually causing a problem, and another bug was making it much harder to see what happened.
=> address various test irregularities and confusions

cli/cli.go, cli/errors.go, cli/meta.go, cli/queryer.go, cmd/fbsql/main.go
This also stubs out an integration test for fbsql.
=> Minor cleanup to some fbsql flags and meta-commands

sql3/planner/expression.go, sql3/sql_complex_test.go
=> compileOrderingTermExpr needs to return alias and not expression

sql3/errors.go, sql3/planner/expression.go, sql3/planner/expressionanalyzercall.go, sql3/planner/inbuiltfunctionsdate.go, sql3/test/defs/defs_date_functions.go
this uses the tiem.date() function
=> FB-1895: Implement DateTimeFromParts

sql3/errors.go, sql3/planner/expression.go, sql3/test/defs/defs_binops.go
Now divide by zero will be reported as SQL errors.
=> Gracefully handle divide by zero

sql3/planner/expression.go, sql3/planner/expressionanalyzercall.go, sql3/planner/inbuiltfunctionsdate.go, sql3/test/defs/defs.go, sql3/test/defs/defs_date_functions.go
FB-1961
Added function and test coverage.
=> Added date_trunc time/date scalar function

api.go, sql3/planner/compileselect.go, sql3/planner/compileshow.go, sql3/planner/executionplannersystemtables.go, sql3/planner/opfeaturebasetables.go, sql3/planner/opsystemtable.go, sql3/planner/wireprotocol.go, sql3/sql_complex_test.go
Renaming 2 system tables:
fb_cluster_nodes --> fb_database_nodes
fb_cluster_info --> fb_database_info
=> renamed 2 system tables

sql3/sql_complex_test.go
=> Add SQL3 Tests: add test coverage for ordering by string, bools, and timestamps

server/handler_test.go
There's no actual way to forcibly sequence our check of the history until after the history has been updated, but it's pretty fast usually, just not always instantaneous. Without this, adding a few millisecond delay in the tracker reliably produces the test failures we kept seeing with an unexpectedly low length of 3. With this, it passes consistently even with the artificial delay.
The query tracker being asynchronous is probably fine, but we need to test it as though it might take a while.
=> retry thing that depends on something asynchronous

sql3/test/defs/defs_bulkinsert.go
Assignment compatibility checking in analyzeBulkInsertStatement is now tested. This isn't checking the values themselves, it's there to make sure the structure is correct for mapping values to columns.
=> Add test coverage in compilebulkinsert.go

dax/storage/storage.go
So we have a problem which is triggered in part by the race detector, but which is actually deeper, but also possibly rare enough to be politely ignored.
The real underlying issue is that sometimes when we have multiple tests running in CI, multiple instances of the CLI test end up using the same postgres database backing for some of their DAX stuff. We have workarounds for this in some places, but not others.
But the *observed symptom* of this is that it can cause a trivial race detector issue where we have one call to `(*Resource).Lock()` and another call to `(*Resource).IsLocked()` which aren't synchronized in any way, so if the race detector spots this, it complains.
We can suppress that very easily by synchronizing these. That does not solve the other possibly-weird problems, so this …
=> hacky workaround: use locking to quiet race detector problems
