- cmd/server.go
- config.go
- ctl/config.go
- executor.go
- executor_test.go
- handler.go
- pilosa.go
- pql/ast.go
- server.go
- server/server.go
A configurable limit has been added to restrict the number of mutating calls in a `pql.Query`. This is to prevents requests from timing out from large queries.
The default is set to 5000 writes per request and is configurable through the configuration file and the command line flags.
Fixes #386.
> Add max-writes-per-requests limit.

- executor.go
- fragment.go
- fragment_test.go
- frame.go
- httpbroadcast/messenger.go
- server.go
- view.go
All tests which use MustOpenFragment now explicitly pass a cacheType parameter.
If this parameter is an empty string, it means that whether the test works
should not depend on the cache type of the fragment. Otherwise the test should
explicitly set the cache type it needs rather than relying on the default.
> change default cache type to ranked

- roaring/assembly_amd64.s
assembly_amd64.s:3: [amd64] hasAsm: wrong argument size 0; expected $...-1
assembly_amd64.s:11: [amd64] POPCNTQ: wrong argument size 8; expected $...-16
assembly_amd64.s:12: [amd64] POPCNTQ: unknown variable x; offset 0 is memory+0(FP)
assembly_amd64.s:17: [amd64] BSFQ: wrong argument size 8; expected $...-16
assembly_amd64.s:18: [amd64] BSFQ: unknown variable x; offset 0 is memory+0(FP)
assembly_amd64.s:28: [amd64] popcntSliceAsm: invalid offset s+8(FP); expected s+0(FP), s_base+0(FP), s_len+8(FP), or s_cap+16(FP)
assembly_amd64.s:43: [amd64] popcntMaskSliceAsm: invalid offset s+8(FP); expected s+0(FP), s_base+0(FP), s_len+8(FP), or s_cap+16(FP)
assembly_amd64.s:63: [amd64] popcntAndSliceAsm: invalid offset s+8(FP); expected s+0(FP), s_base+0(FP), s_len+8(FP), or s_cap+16(FP) …
> roaring: fix vet issues with the assembly code

- Dockerfile
- Makefile
I've removed the micro docker stuff from this PR and only include updates that fix pilosa binary version, etc. since docker recently introduced a new feature called multistage builds which enables creating the micro image without a build container.
Also, our submission to the official images may require us to keep the docker stuff in its own repo.
> docker update

- cluster.go
- config.go
- executor.go
We needed a way for users of v0.2 to—while replacing a down node—prevent reads from going to the replacement node until the sync process is complete.
> Add Cluster.UnavailableNodes support to skip reads on certain nodes (for v0.2).

- Dockerfile
before:
```
Step 6/13 : RUN wget ${GLIDE} -O /go/glide.tar.gz -q     && tar xf /go/glide.tar.gz     && mv /go/linux-amd64/glide /go/bin     && [ "$(sha256sum /go/bin/glide | cut -d' ' -f1)" = "$GLIDE_HASH" ]     && cd /go/src/github.com/pilosa/pilosa     && make vendor     && CGO_ENABLED=0 go install -a -ldflags "$ldflags" github.com/pilosa/pilosa/cmd/pilosa
---> Running in e2a6fcdf5930
The command '/bin/sh -c wget ${GLIDE} -O /go/glide.tar.gz -q     && tar xf /go/glide.tar.gz     && mv /go/linux-amd64/glide /go/bin     && [ "$(sha256sum /go/bin/glide | cut -d' ' -f1)" = "$GLIDE_HASH" ]     && cd /go/src/github.com/pilosa/pilosa     && make vendor     && CGO_ENABLED=0 go install -a -ldflags "$ldflags" github.com/pilosa/pilosa/cmd/pilosa' returned a non-zero code: 1
make: *** [docker] …
```
> provide details on glide checksum mistmach

- executor.go
- executor_test.go
- pql/ast.go
The TopN() call now supports an `inverse` boolean argument to specify if the call should operate on the standard view or the inverse view.
Fixes #515.
> Add inverse TopN() support.

- roaring/roaring.go
- roaring/roaring_internal_test.go
I think these are all real, but let me know if I've just completely misunderstood how this is supposed to work. Hoping to get at least 2 reviews since we're pretty deep into the bowels here.
in order of the diff:
1. When the start and end of the range fall in the same word, special handling
is needed to "mask" off the beginning and end of the word simultaneously to
avoid counting bits at the beginning or end of the word that aren't in the
range.
2. `i++` is needed at the end of the first partial word to avoid counting this
word in the next block.
3. the shift amount for right shifts is 64 - (end % 64) rather than just end
% 64. If end is (e.g.) 68, then 68 - 64 is 4 and we are only interested in the
first 4 bits of the word, so we must right shift by 60 bits, not 4 bits.
> fix 3 separate bugs in bitmapCountRange

- cmd/generate_config.go
- cmd/server.go
- config.go
- ctl/generate_config.go
- ctl/server.go
- glide.lock
Renames `config` to `generate-config` and implements a new `config` command that generates the configuration file based on the current state instead of printing a static string.
Fixes #375, #366.
> Implement 'config' CLI command.

- Makefile
`make release` now produces a 32-bit linux binary.
> Add 32-bit build to release process

- server.go
was getting an error from not specifying internal hosts properly (i think) but couldn't tell exactly where it was from by the error message.
> discriminate error messages in server.Open

- attr.go
- attr_test.go
Changes the behavior of `AttrStore.SetAttrs()` to first verify that the attributes haven't changed using a read-only lock before obtaining a write lock to update the attributes.
Since the write lock serializes access, the previous insert time sufferred lock contention when inserting a lot of duplicate attributes. With the `RWMutex`, reads can be done in parallel so multiple requests don't block each other.
Below is a simple benchmark showing the performance at 1, 5, & 10 goroutines:
```
BenchmarkAttrStore_Duplicate          100000      137120 ns/op      8428 B/op       76 allocs/op
BenchmarkAttrStore_Duplicate-5        100000      417459 ns/op      8431 B/op       76 allocs/op
BenchmarkAttrStore_Duplicate-10       100000      139466 ns/op      8433 B/op       76 allocs/op
```
``` …
```
> Check for duplicate attributes under read lock on insert.

- roaring/roaring.go
- roaring/roaring_internal_test.go
This is a 15x performance boost to TopN queries with one Bitmap on the NYC taxi dataset. 
e.g. ```TopN(Bitmap(frame=passenger_count, rowID=1), frame=total_amount_dollars)```
Results appear to be the same with both implementations. 
Basically the idea is to iterate over the array container rather than the bitmap container since the bitmap container basically means iterating over each bit of each uint64 (65536 bits), vs guaranteed <4096 uint32s in the array container.
I believe this is strictly faster than the previous implementation, but let me know if there are cases where performance would be lost (or if it's just incorrect).
> rewrite intersectCountArrayBitmap for perf test

- roaring/roaring.go
should be a small perf win - except when the output is empty
> set n based on array length instead of incrementing repeatedly

- server.go
Return an error if the BroadcastHandler CreateFrameMessage encounters an Index that does not exist.
> BroadcastHandler handle missing index

- docs/tutorials.md
Properly indent `Fields.Mappers.Max` field in example JSON.
> Minor docs fix, indent in JSON

- Makefile
- cmd/server_test.go
- pilosa_test.go
- pql/parser_test.go
- roaring/roaring_test.go
- server.go
- server/server_test.go
- statsd/statsd_test.go
- test/test.go
Turning off IPv6 causes the tests to fail because the Go `net.Listen()` function obtains a `[::]` address when using a `localhost:0` bind address. Looking through the Go source code, I don't see a good way to fix that.
This change adds a test flag to allow users to specify the network name when running the test:
```sh
go test github.com/pilosa/pilosa/server -network tcp4
```
Fixes #348
> Fix failing tests when IPv6 is disabled.

- ctl/backup_test.go
- ctl/bench_test.go
- ctl/check_test.go
- ctl/config_test.go
- ctl/export_test.go
- ctl/generate_config_test.go
- ctl/import.go
- ctl/import_test.go
- ctl/inspect_test.go
- ctl/restore_test.go
- ctl/server_test.go
- ctl/sort_test.go
Package ctl is now 75% percentage cover. There are 2 tests for check.go and inspect.go I need to spend more time to understand roaring, that they both need a correct roaring bitmap file to test happy path to improve its coverage to increase more percentage cover, I did add ToDo in the file to come back later. 
The other thing is I standup a server on tests, which is similar what pilosa_test does to standup pilosa server on random port. I’m not sure if there’s a better way to reuse code in pilosa_test (like import package?) rather than duplicate many code. 
Any recommendation @jaffee
> Improve test coverage for ctl package

- Makefile
If glide is not installed, then $(GLIDE) is empty, so I guess the $(GLIDE)
target gets ignored? The impetus for this is that `make install` was failing on
a fresh ubuntu instance saying glide wasn't found.
> make sure glide is installed before `glide install`

- Makefile
Somehow a hyphen entered our Makefile by accident. This just removes it.
> Remove unintentional dash from LDFLAGS

- holder_test.go
- view.go
Adds test coverage for various failing `Holder.Open()` scenarios.
Fixes #583.
> Add Holder test coverage.

- Makefile
`make cover-viz` will now generate an HTML coverage report for the entire codebase.
> Add coverage tools to Makefile

- server/server_test.go
Test create input definition across 2 servers
> Test create input definition across 2 servers

- roaring/roaring.go
- roaring/roaring_test.go
Fixes a bug that caused a panic when calling `bitmap.Slice()` on a bitmap that had container transitions from run to array and array to run.
> Standardize the default iterator val for j to -1 for both arrays and runs

- roaring/roaring_test.go
this commit fills in some gaps in tests related to `intersect**` operations.
> Roaring intersect tests

- attr_test.go
- client_test.go
- cluster_test.go
- ctl/backup_test.go
- ctl/bench_test.go
- ctl/export_test.go
- ctl/import_test.go
- ctl/restore_test.go
- executor_test.go
- fragment_test.go
- frame_test.go
- handler_test.go
- holder_test.go
- index_test.go
- stats_test.go
- test/attr.go
- test/client.go
- test/cluster.go
- test/executor.go
- test/fragment.go
- test/frame.go
- test/handler.go
- test/holder.go
- test/index.go
- view_test.go
This refactors testing utilities from the various *_test.go files in the main pilosa package to `pilosa.test`. This removes the duplicated test utilities from pilosa.ctl as they can now be imported.
Fixes #602 
> Refactor test utilities into importable package.

- fragment.go
- fragment_test.go
- frame.go
- frame_test.go
- pilosa.go
- view.go
This pull request adds support for set/get range values at the `Frame`, `View`, and `Fragment` levels.
Fixes #617.
> Set & retrieve field values.

- webui/assets/style.css
Noticed in the web console running the query from getting started tutorial Bitmap(frame="stargazer", stargazer_id=14) would overflow the resulting text.
Text escaping its div container. Did not create an issue since this is a small css fix for some minor aesthetics. 
Fixes #
I looked at the existing issues but did not see anything related to this. 
> webui style update

- docs/getting-started.md
- handler.go
- handler_test.go
- index.go
- input_definition.go
- input_definition_test.go
Update input definition to handle adding timestamp. 
@travisturner: this doesn't block the input-definition, I can send another PR to master after check in input-definition if you have no time to review this now. Still need to update getting-start repo & doc with timestamp though
> add action to handle timestamp

- fragment_test.go
Randomized tests were failing in travisCI when a column size was set to 0 in the test.
This fix prevents columnN from being 0.
> adjust columnN range to avoid divide-by-zero error in travisCI

- docs/configuration.md
Adds configuration docs for `gossip-seed` as requested by #717.
> add gossip-seed to configuration docs

- cmd/server_test.go
- config.go
- config_test.go
- fragment_test.go
- pilosa.go
- pilosa_test.go
- server/server.go
Add a validation step after parsing configuration parameters.
Add tests to Configuration.
Fixes #
712 check the the broadcast port is in the internal-hosts set.
Return a meaningful error when attempting to run a configuration that would otherwise have failed silently.
> 712 Configuration validation

- attr.go
This separates the attribute cache from the attribute store and adds a mutex, which fixes a concurrent map access bug reported in #724.
Fixes #724
> Add mutex for attribute cache. Fixes #724.

- executor.go
- executor_test.go
- pilosa.go
This commit adds support in the PQL language to set field values.
Fixes #618
> Add PQL support for field values.

- handler.go
- handler_test.go
Previously, if Pilosa experienced a panic while handling a request, it would print the stack trace, abort handling of the current request, and continue handling other requests as normal - the client was left in the lurch with an unexpected EOF. This PR recovers from all panics in handlers explicitly and returns an internal server error to the client along with a stack trace so the client may handle the failure more gracefully.
Fixes #
> add recovery in top level handler

- fragment.go
- roaring/roaring.go
- roaring/roaring_test.go
Count and CountRange results where not matching due to incorrect handling of less than edge case
Fixes Unreported bug
> CountRange was incorrect if rangekey was prior to inital container

- handler.go
fix log which treats time.Duration as secs instead of ns
Fixes #
no associated issue
> fix log which treats time.Duration as secs instead of ns

- roaring/roaring.go
- roaring/roaring_internal_test.go
- roaring/roaring_test.go
A few bugs in Bitmap.CountRange code. Both occurred in the case where `search64` returned a negative number because the container key was not found in the list of container keys. The negative number returned is `-1 * (<index where the number should be> + 1)` That  `+ 1` was not being taken into account in the CountRange method, although it is taken into account at other locations where `search64` is used in roaring.go. The reason `search64` doesn't just return the negative index is because the index might be 0 in which case there would be no way to distinguish between "value was found at position 0" and "value was not found but would be located at position 0" 
Fixes #770 and one other bug which was discovered during the process but not ticketed.
This is the checklist that the reviewer …
> Countrange bug

- roaring/roaring.go
- roaring/roaring_internal_test.go
When a run ended the container (i.e. contained column 65535), then the for loop
would increment the 16-bit value to 0, at which point it was still <= 65535.
> Fix infinite loop in bitmap-to-array conversion.

- roaring/roaring.go
- roaring/roaring_internal_test.go
The method `differenceRunRun` was creating an output container (with default n=0), and n was never getting updated. Normally this was handled by the `differenceRunIterator`, but that's not used in `differenceRunRun`.
> set container.n in differenceRunRun

- executor.go
- executor_test.go
- fragment.go
- fragment_test.go
- frame.go
- pql/ast.go
- view.go
This pull request adds the ability to filter bitmaps based on field range values.
```
Range(frame=f, foo == 20)
Range(frame=f, foo < 20)
Range(frame=f, foo <= 20)
Range(frame=f, foo > 20)
Range(frame=f, foo >= 20)
```
> Add field Range() support to Executor.

- client.go
- cmd/import.go
- ctl/import.go
- ctl/import_test.go
- time.go
Implements auto-creating the schema on import
Resolves #765 
Example:
```
$ pilosa import --sort --create -i repo -f stargazer stargazer.csv --frame-inverse-enabled --index-time-quantum YM --frame-cache-size 3000
```
> Enables auto-creating the schema on imports; Resolves #765

- executor.go
- fragment.go
- fragment_test.go
- frame.go
- frame_test.go
- pilosa.go
- pql/ast.go
- pql/ast_test.go
- pql/parser.go
- pql/parser_test.go
- pql/scanner.go
- pql/scanner_test.go
- pql/token.go
- view.go
The PQL looks like:
```
Range(frame=f, field0 >< [200,610])
```
One thing I noticed while implementing this is that it doesn't seem
like `FieldRange()` is used in either `Frame` or `View`; the Executor
calls `Fragment.FieldRange()` directly. The problem with this is that
the offset logic is calculated in the Frame, but since the Executor
doesn't go through Frame, then the Executor also has to calculate
the offset before calling `Fragment.FieldRange`. We should unify this
logic somewhere. Note, this applies to both `FieldRange` and
`FieldRangeBetween`.
> Implements BETWEEN for Range queries.

- pql/ast.go
- pql/ast_test.go
Fixes a bug that was causing an error when parsing a range condition in a multi-node cluster.
> Don't include an equal sign in the string representation of a Condition

- roaring/roaring.go
- roaring/roaring_test.go
When the difference of two run containers resulted in an empty
container, that container would be a run container with no runs.
The Iterator was expected there to be at least on run in
`container.runs`. This fix protects against that and adds tests
for that case.
> Fix panic when iterating over an empty run container.

- docs/api-reference.md
- docs/client-libraries.md
- docs/getting-started.md
- docs/input-definition.md
- docs/query-language.md
- docs/webui.md
> Deprecate row/column labels

- executor.go
- executor_test.go
- fragment.go
- fragment_test.go
- frame.go
- pql/parser.go
- pql/parser_test.go
- pql/scanner.go
- pql/scanner_test.go
- pql/token.go
In the example use-case where a `field` represents a calendar day, and the field's value range is `[0-1439]` such that a value represents a particular minute of the day, then if we want to support a range query that spans days, we can make the query more efficient by returning the `not-null` rows for any full field (day) in the middle of the range.
For example, if we want to query a 48-hour range like `2017-10-03T10:28 to 2017-10-05T10:27`, then we effectively want this:
```
Union(
Range(frame=f, d20171003 >= 628),
Range(frame=f, d20171004 >< [0, 1439]),
Range(frame=f, d20171005 < 628)
)
```
The first pass at this PR doesn't change the query language. The second Range() query in the example above will return the `not-null` row for that field. This applies to any case where the query range …
> FieldNotNull for more efficient BETWEEN queries

- cmd/root.go
- cmd/server_test.go
- docs/configuration.md
The dot (`.`) cannot be used in bash environment variable names, so any configuration item with a dot in it such as `cluster.hosts` wasn't available as an environment variable (``PILOSA_CLUSTER.HOSTS` is not a valid bash name). This PR replaces dot with underscore for environment variables, so `cluster.hosts` can be used as `PILOSA_CLUSTER_HOSTS` in bash.
> Fix dot in env

- Gopkg.toml
constraining bolt to a specific revision is causing dependency issues with the pdk - best practice is to constrain to a version I believe (theoretically the minimum which you require)
Fixes #
> constrain bolt to version rather than specific revision

- cluster.go
- handler.go
- security_manager.go
In order to guarantee system state, only applicable endpoints are exposed.  This is achived by providing two different router mux, a restricted router and the normal router.
> added endpoint protection for cluster resize

- executor.go
The idea here is for Pilosa to behave better under high query load where a node
might be making many connections to the other nodes in the cluster in order to
support lots of concurrent batches of SetBit queries (for example). By allowing
for more idle connections and more idle connections per host, we reduce
connection churn, and allow more connections to be reused rather than creating
new ones and potentially having many stale sockets in the TIME_WAIT state. See
https://github.com/golang/go/issues/16012
Fixes (hopefully) #906
> bump http client's MaxIdleConns and MaxIdleConnsPerHost

- client.go
This helps "connection reset" issues when the cluster is under high query load
from many clients.
This also brings in the default http transport options which were (mistakenly?)
removed by the TLS work. I'm not sure what the ramifications would be of using a
blank http.Transport{} instead of http.DefaultTransport, but it seems best to
avoid a sweeping change.
Fixes #906 
> bump MaxIdleConns(PerHost) like v0.7

- docs/input-definition.md
- handler.go
- handler_test.go
- index.go
- index_test.go
- input_definition.go
- input_definition_test.go
The primary key name defaults to `DefaultColumnLabel`. Primary key field is optional. If not given and there are other fields, a new field with `Name=DefaultColumnLabel, PrimaryKey=true, Actions=[]` is added to the input def.
Fixes #810 
> Removes column/row labels for input definition. Resolves #810

- docs/query-language.md
BSI Range queries support five different operators that, previously, weren't clearly specified anywhere except the source code. Also, the BETWEEN operator is unique to pilosa, and searching for it or "between" in the docs didn't return anything helpful.
> Add search-friendly documentation for BSI range query syntax

- cluster.go
- cluster_test.go
- holder.go
- holder_test.go
- server.go
- test/cluster.go
Implements a Holder.Peek() function, and breaks out
Cluster.ListenForJoins() into a separate method that can be started
after the Holder finishes loading data.
TODO:
> WIP: don't block joining nodes while coordinator loads data.

- diagnostics/diagnostics.go
- diagnostics/diagnostics_test.go
Fixes the issue where the local version is greater that the reported latest from Pilosa.com.
Fixes #966 
> fixed version check when local is greater than pilosa.com

- server.go
- server/server_test.go
This causes CountOpenFiles to return an error instead of crashing if it can't call out to `lsof`.
Fixes #967 
> Fix CountOpenFiles() fatal crash

- executor.go
- executor_test.go
- frame.go
This modifies Executor.executeFieldRangeSlice() so that LT[E] and GT[E] Range() queries return all not-null if selected range fully encompases valid field range.
Fixes #876
> Fix edge case with Range() calls outside field Min/Max. Fixes #876.

- client.go
- client_test.go
- ctl/common.go
- executor.go
- fragment.go
- handler.go
- holder.go
- holder_test.go
- server.go
- server/server.go
- server/server_test.go
- test/client.go
- test/executor.go
@tgruben I recreated this directly on top of the v0.8 branch because the other PR looked weird... had a bunch of extra commits and a merge conflict.
@codysoyland can we cut a v0.8.2 once this is in place
Fixes #
> Single http client 0.8

- cluster.go
- fragment.go
- server.go
Fixes #914 
Group the writes in syncBlock by MaxWritesPerRequest.  If nodes are really of of sync the required writes could exceed MaxWritesPerRequest.  
> group the write operations in syncBlock by MaxWritesPerRequest

- gossip/gossip.go
- server/server.go
- server/server_test.go
Create a custom memberlist NetTransport (which will bind to an available
port when port = 0 in the configuration). This allows us to bind
to dynamic ports in tests while at the same time determining a valid
seed for the cluster.
Fixes #951 
> Resume test: TestMain_SendReceiveMessage

- broadcast.go
- broadcast_test.go
- client.go
- gossip/gossip.go
- handler.go
- server.go
- server/server.go
- server/server_test.go
The `Broadcaster` interface function `SendSync` is now handled through a new `/cluster/message` endpoint. This allows us to gather and return errors that any node in the cluster could generate through any of the broadcasted messages like: `CreateIndexMessage`
Additional, `Broadcaster.SendAsync` is passed through to a different `SendAsync` function which is part of the `Gossiper` interface.
This PR contains the work started by @raskle in #984, but I adjusted it a bit so that the `BroadcastHander` interface didn't require a `SendSync` function.
Fixes #973 
> 973 sendsync

- .travis.yml
Use `go test` instead of `goveralls` as main CI test command. Call `goveralls` in after_success block. This will prevent `goveralls`-specific errors from breaking the build.
Fixes #1009
> Use `go test` instead of `goveralls` as main CI test command

- Gopkg.lock
- Gopkg.toml
- client.go
- handler.go
- holder.go
- server.go
Adds local and cluster IDs. Each node has a unique *local* ID. Local IDs are saved as file `ID` in the data directory, Local ID of the first node is used as the *cluster* ID of all nodes.
~WIP: In order to retrieve a cluster ID, the first node must be up and running. Other nodes should wait a bit until then to set their cluster IDs.~ This seems to work, since other nodes wait for the 1st node.
Implements #987 
Sample messages from a 3 node cluster:
```
{"Cluster":"01.pilosa.local:10501","ClusterID":"fa01fc81-daad-40bc-8f57-52924d46e623","GoRoutines":16,"Host":"01.pilosa.local","LocalID":"fa01fc81-daad-40bc-8f57-52924d46e623","NumCPU":8,"NumFrames":1,"NumIndexes":1,"NumNodes":3,"NumSlices":1,"OpenFiles":23,"Version":"v0.8.0-47-g8d587d7","uptime":1} …
```
> Adds local and cluster IDs

- server.go
Addresses a possible race condition that happens when `NodeStatus` is shared by the cluster just before a starting node has opened its `Holder`.
> make sure the holder has opened before merging NodeStatus

- test/pilosa.go
Pilosa runs on ephemeral ports with temporary storage.
> add test helper for starting a new pilosa instance

- server/server_test.go
There is a race condition where the diagnostics background job is requesting data from memberlist. In some cases, memberlist hasn't finished opening and causes a panic in the background job. This PR turns off the diagnostics job for tests in `pilosa/server`.
> disable diagnostics in server tests

- Gopkg.lock
- Gopkg.toml
- server.go
- server/server_test.go
datadog statsd client contained a race condition - was fixed in master
Server.Logger contained a race where multiple loggers could write to the same
output io.Writer
TestMain_FrameRestore contained a race where it tried to change a cluster's
nodes while it was running (which conflicted with antiEntropy reading that
state).
Fixes #
> fix a number of data races

- holder.go
- holder_test.go
- server.go
This PR adds a few stats (timers and histograms) around the AntiEntropy process.
> add some statsd calls to HolderSyncer

- cluster.go
race detector found multiple goroutines calling `MergeRemoteState` which writes to `Node.status`.
> add lock around Node.status to avoid race condition

- Dockerfile
- Makefile
- server/default.go
- server/release.go
- server/server.go
- server/server_test.go
- test/pilosa.go
This makes sure diagnostics aren't enabled during `go test` or unless the `release` build constraint is enabled. This replaces existing logic that disabled diagnostics by use of config flags.
> Enable diagnostics via build constraint to prevent from running in tests

- config_test.go
- ctl/common.go
- diagnostics/diagnostics.go
- diagnostics/diagnostics_test.go
- pilosa_test.go
- server/default.go
- server/release.go
- server/server.go
- stats_test.go
- test/attr.go
- test/client.go
- test/cluster.go
- test/executor.go
- test/fragment.go
- test/frame.go
- test/handler.go
- test/holder.go
- test/index.go
- test/pilosa.go
- test/pilosa_test.go
- test/test.go
- version.go
Adds the license header to source code files for which it was missing.
@codysoyland there are a couple of build-tag-related files in `/pilosa/server` which don't have the header. Can you review those?
> ensure that the license header is included in all source files

- bitmap_test.go
- roaring/roaring.go
- roaring/roaring_internal_test.go
There was a case where the Bitmap iterator logic could skip over a bit in a run
container if 1. the run container was not the first container in the bitmap, and
2. The first run in the run container had only one bit.
The bug was due to how the iterator was initialized with iterator.Seek(0) which
sets up the initial values of itr.i,j,k based on the type of the first
container. It was failing to set itr.k to -1 unless the first container was an
RLE container. itr.k is only used by RLE containers in the iterator, and must be
set to -1 when an RLE container is encountered. When Iterator.Next() encountered
the run container and itr.k was set to 0, it checked to see if itr.k <= run.last-run.first, and if so it assumes that it was finished with the run and moved to
the next one. run.last - …
> fix bug where count and bitmap queries could return different numbers

- cmd/server_test.go
- config.go
- config_test.go
- ctl/server.go
- pilosa.go
- server/cluster_test.go
- server/server.go
- server/server_test.go
- test/pilosa.go
- test/pilosa_test.go
Changes the configuration parameter `Cluster.Type` (which was a string option of `[none, static, gossip]`) to `Cluster.Disabled` which is a boolean.
Based on a discussion in #595.
> Changes configuration cluster.type (string) to cluster.disabled (bool)

- server/cluster_test.go
- test/pilosa.go
- test/pilosa_test.go
This PR contains the code from #1076 after addressing merge conflicts.
now using concrete URI values everywhere instead of pointers to them
> fix bug in NewServerCluster where each host was its own coordinator

- roaring/roaring.go
- roaring/roaring_internal_test.go
When the final value in the array was 65535 and the run also spanned 65535, then an overflow caused the run {0, 65535} to be appended to the run slice. This PR prevents that by breaking out of the run loop before getting to the overflow.
Fixes #1103
> avoid overflow bug in differenceRunArray (v0.8)

- roaring/roaring.go
- roaring/roaring_internal_test.go
When the final value in the array was `65535` and the run also spanned `65535`, then an overflow caused the run `{0, 65535}` to be appended to the run slice. This PR prevents that by breaking out of the run loop before getting to the overflow.
Fixes #1103 
> avoid overflow bug in differenceRunArray

- docs/administration.md
- docs/configuration.md
This PR cleans up the `metrics` config options.
Fixes #762
> clarify the options in configuration for metrics.service

- roaring/roaring.go
- roaring/roaring_internal_test.go
Fixes a shift logic bug in bitmapZeroRange that was causing an overflow-like condition.
This addresses the follow up bug reported in #1103.
> fixes a shift logic bug in bitmapZeroRange

- roaring/roaring.go
- roaring/roaring_internal_test.go
that was causing an overflow-like condition
> fixes a shift logic bug in bitmapZeroRange (v0.8)

- roaring/roaring.go
- roaring/roaring_helpers_test.go
- roaring/roaring_internal_test.go
This PR includes a little more organized test coverage of the roaring container operations (`intersect`, `union`, `difference`, and `xor`). There are still additional test that we can add (for example, the bits set at the boundary of the bitmap uint64), but this provides a starting place. 
Also included are fixes for bugs found by running these tests.
Fixes #857 
> Roaring test templates

- docs/configuration.md
cluster type http is no longer valid - this removes it from documentation
Fixes #
> remove cluster type http from docs

- docs/query-language.md
column labels are deprecated and the docs' usage of columnID vs repo_id was
inconsistent.
Fixes #
> remove column label repo_id from query language docs

- frame.go
- server.go
- view.go
This PR fixes an issue where a broadcast message (`CreateViewMessage`) was being sent on any schema check. Now, if a view is not created during the check, then no message is sent.
This also moves the logic with disables caching on BSI field into the `view.Open()` method so that it's considered on startup.
> prevent excessive sendSyce (createView) messages.

- config.go
- ctl/server.go
- ctl/server_test.go
- docs/configuration.md
- gossip/gossip.go
- server/cluster_test.go
- server/server.go
- test/pilosa.go
This adds support for a comma-separated list of URIs in the `gossip.seed` configuration variable.
> Add support for lists of gossip seeds for redundancy

- gossip/gossip.go
- test/pilosa.go
This PR fixes an issue where setting up the memberlist transport was not considering the address scheme.
Fixes #1141 
> handle the scheme correctly in config.Bind

- roaring/roaring.go
I noticed this comment was pretty wrong a while ago, but finally fixing it. Note that I'm explicitly saying that an array container COULD have more than 4096 values, and all the code should still work, and more generally, any container type can represent any set of bits and all operations should still perform. This is consistent (I think) with our new testing strategy, so I think it's good to be explicit about it.
Fixes #
> make container struct description more accurate

- config.go
- ctl/server.go
- ctl/server_test.go
- server/server.go
This PR removes the deprecated GossipPort (`--gossip-port`) and GossipSeed (`--gossip-seed`) config options. It also updates the `Cluster.Hosts` help text to clarify that it is only to be used for testing.
> remove old GossipPort and GossipSeed config options

- Gopkg.lock
- broadcast.go
- diagnostics.go
- diagnostics_internal_test.go
- diagnostics_test.go
- gc.go
- gopsutil/systeminfo.go
- gopsutil/systeminfo_test.go
- server.go
- server/server.go
This is an alternative to #1161 that, instead of creating a Diagnostics interface to move the gopsutil dependency out of `package pilosa`, it creates a `SystemInfo` interface with a `gopsutil` implementation. This also removes the `gobreaker` dependency and cleans up a few related things.
> Refactor Diagnostics: Move to main package, remove gobreaker, add SystemInfo abstraction for gopsutil dependency injection

- roaring/roaring.go
While looking at benchmarks as a possible go compiler benchmarks,
I've tried some optimizations by hand:
Move len(b.bitmap) load out of the loop.
Remove some type conversions.
Use (x >> off) & 1  to get offs bit, instead of  x & (1 << of)f >> off.
This produces nice speed-up and passes go test roaring.
name                                    old time/op  new time/op  delta
Bitmap_IntersectionCount_ArrayRun-6     2.06µs ± 0%  1.57µs ± 0%  -24.04%  (p=0.000 n=10+9)
Bitmap_IntersectionCount_BitmapRun-6    2.24µs ± 0%  2.24µs ± 0%     ~     (p=0.913 n=10+9)
Bitmap_IntersectionCount_ArrayBitmap-6  2.06µs ± 0%  1.56µs ± 1%  -24.05%  (p=0.000 n=9+10)
> roaring: speed-up intersectionCountArrayBitmap

- attr.go
- boltdb/attrstore.go
- fragment.go
- fragment_test.go
- frame.go
- holder.go
- index.go
- server.go
- server/server.go
- test/attr.go
- test/fragment.go
- test/holder.go
- test/pilosa.go
- view.go
- view_test.go
This PR creates `AttrStoreGenerator` and `AttrStore` interfaces, and moves the boltdb dependency out to an implementation of these interfaces.
We should probably add an in-memory implementation to use in testing. Currently, the tests have been modified to use the boltdb implementation.
Fixes #1096 
> put BoltDB behind AttrStore interface

- gossip/gossip.go
- server/cluster_test.go
There is no need to set the gossip seed to the local node's bind address (e.g. in the case of a one-node cluster). This PR removes that default, and moves the logic to the `Seeds()` method which is actually only used for testing.
Fixes #1172 
> Default gossip seed should be empty instead of local bind address

- cluster.go
- cmd/server.go
- config.go
- ctl/server.go
- diagnostics.go
- diagnostics_internal_test.go
- docs/configuration.md
- fragment.go
- frame.go
- gossip/gossip.go
- handler.go
- handler_test.go
- holder.go
- holder_test.go
- index.go
- logger.go
- server.go
- server/cluster_test.go
- server/server.go
- stats.go
- stats_test.go
- statsd/statsd.go
- statsd/statsd_test.go
- test/handler.go
- test/holder.go
- test/logger.go
- test/pilosa.go
- view.go
This PR adds a `Logger` interface so all objects share the same logger.
It also adds functional options to `NewGossipMemberSet` to support supplying a `log.Logger` and/or a `Transport`.
Fixes #631 
> Clean up logger; make it honor --log-path flag.

- executor.go
- server/server_test.go
When `slices` were sent to a remote node in the case of an inverse query, it actually represented `inverseSlices`. This PR makes sure that the remote node uses that value correctly.
> make sure that slices is treated as inverseSlices on inverse calls

- api.go
- apimethod_string.go
- docs/api-reference.md
- handler.go
- handler_test.go
Removed the PATCH frame endpoint, which supported the ability to modify the timeQuantum for an existing frame. For now, setting timeQuantum will be restricted to frame creation.
Fixes #1218 
> remove PATCH frame endpoint

- broadcast_test.go
- server.go
- server_test.go
- test/pilosa.go
also fix bug where broadcast_test tried to listen on localhost:10101
This was broken by some recent refactoring - I noticed it while trying to import a bunch of genome data into a Pilosa cluster. It was not caught by any of our current integration type tests because they use a 10 minute anti entropy interval by default.
Fixes #
> fix nil client bug in monitorAntiEntropy (and test)

- holder.go
- server.go
This adds a log line to `$DATA_DIR/.startup.log` with the current time and pilosa version. We can use this for debugging in the future if need be.
Fixes #391 
> Log time/version to startup log (Fixes #391)

- api.go
- handler.go
- handler_test.go
Adds `/info` endpoint which returns the slice width. We can also return other compile time server properties from this endpoint, such as `/version`.
Fixes #1232 
> Added /info endpoint. Fixes #1232

- broadcast_test.go
- server.go
- server/server.go
> Make sure ~ is expanded in NewServer; BroadcastReceiver uses temp path

- api.go
- client_test.go
- ctl/backup_test.go
- ctl/export_test.go
- ctl/import_test.go
- ctl/restore_test.go
- server.go
- test/handler.go
`API.URI` wasn't being used, so I removed it from the struct and from everywhere it was being set.
> API.URI was not being used. removed it.

- gossip/gossip.go
- server/server.go
`GossipMemberSet.Logger` wasn't being set and would occasionally panic during CI when it tried to log to a `nil` logger.
> make sure gossipMemberSet.Logger is set during server setup

- holder.go
> Wrap errors in holder

- server/cluster_test.go
Several cluster resize tests employed a `time.Sleep()` prior to checking cluster state in order to give the test cluster time to settle. This PR replaces that fixed sleep with a periodic poll using a smaller sleep time and a maximum number of attempts.
> adjust cluster state tests so they aren't so dependent upon a sleep

- server.go
An earlier version of this patch, #1019, was erroneously removed during a merge.
> Close HTTP handler gracefully (Fixes #1018)

- server.go
An earlier version of this patch, #1019, was erroneously removed during a merge.
This is a duplicate of #1018 that applies to v0.10.
> Close HTTP handler gracefully (Fixes #1018) (v0.10)

- Gopkg.lock
- ctl/generate_config.go
- ctl/generate_config_test.go
- server/config.go
- server/server_test.go
The generate-config command was printing a fixed string rather than calling
NewConfig() which is the canonical source for default config. I also noticed
that we were depending on two different toml libraries, and so collapsed that to
a single one. We have to use pelletier rather than BurntSushi because the viper
library that we use depends on pelletier.
There is no ticket for this specifically, but it removes the last vestiges of #1217, so Fixes #1217
> fix generate-config command, use single toml lib

- executor.go
- executor_test.go
This PR removes the `frame` argument from `Range()` queries, so instead of `Range(frame=f, f > 10)` the query would be `Range(f > 10)`.
> Remove frame argument from Range() queries.

- cmd/import.go
- ctl/import.go
- ctl/import_test.go
This PR removes the `field` flag from the `pilosa import` command. Instead of relying on the flag to determine how to handle the import data, the importer now requests the schema from the pilosa server in order to determine `frameType`.
Fixes #1353 
> remove field flag from pilosa import command

- attr.go
- fragment_internal_test.go
- index_internal_test.go
- index_test.go
In preparation for #1352, this PR moves fragment tests into the `pilosa` package.
It also adds an in-memory implementation of `AttrStore`.
> move fragment_test into the pilosa package (internal)

- api.go
- client.go
- client_test.go
- executor.go
- executor_test.go
- field.go
- fragment.go
- fragment_internal_test.go
- handler_test.go
- holder.go
- holder_test.go
- stats_test.go
- test/fragment.go
- test/holder.go
- view.go
- view_test.go
This PR un-exports most of the methods on `Fragment`. Still remaining are those methods which involve syncing and caching. Those will need to be addressed along with the internal sync logic.
Note that this required creating a `Field.Row()` method which, confusingly, returns a `Row` made up of a single slice (`RowSegment`). Currently it's only used for tests, but I think we should decide how best to approach tests needing to get a `Row` and not really needing multi-slice data.
> Unexport (some) fragment methods

- server.go
- server/server.go
check out the individual commits
Fixes #
> More messaging simplification

- cluster_internal_test.go
- executor.go
- field.go
- holder_test.go
- http/handler_test.go
- test/field.go
- test/holder.go
- utils_internal_test.go
This PR removes the `view` argument from `Field.SetBit()` and `Field.ClearBit()`.
> remove view argument from Field.SetBit and Field.ClearBit

- cluster.go
- server.go
- server/server.go
removes the broadcaster field from the server. The server itself was almost always the broadcaster - only one test was depending on server having a NopBroadcaster, and that was fixed by having cluster not broadcast node state changes when clustering is disabled.
Fixes #
> remove broadcaster from server

- http/translator_test.go
- mock/translator.go
- server/handler_test.go
- server/server.go
- server_test.go
- test/pilosa.go
This adds functional options for for server.Command so that ServerOptions can be injected. Refactored existing MainOpts to use ServerOptions instead. Used in TranslateStore tests for mock injection. This will allow us to remove the TranslateStore from the API struct.
> Add CommandOptions and use OptCommandServerOptions to inject mock TranslateStore

- broadcast_test.go
- cluster.go
- gossip/gossip.go
- server.go
- server/server.go
- test/pilosa.go
pilosa.Server now implements StatusHandler and EventReceiver and needs only
start a gossip memberset. A gossip member set now takes a server as an argument
explicitly and the maze of handlers and receivers and the starting sequence is
somewhat simplified.
Server now trivially implements EventHandler by passing the call along to its
Cluster object which has the actual implementation. This means that less things
will need to refer to cluster.
partially address #1247 
> consolidate gossipEventReceiver into gossip member set

- broadcast.go
- cluster.go
- cluster_internal_test.go
- gossip/gossip.go
- server.go
- server/server.go
- test/pilosa.go
since the gossip MemberSet has access to Server, it wasn't really necessary to
pass it a Node object when calling Open on it from Cluster. The end goal is to
have it be removed from Cluster entirely, and have it be Opened externally, and
this is a step toward that.
Exposing Node method on Server doesn't really expose any more than was already
there as the same info can be gotten from LocalStatus with a bit of type
casting. I figured adding the method was a little cleaner, and we could collapse
all the functionality when the dust has settled.
The Cluster.open method has been broken into two parts - one of which happens
earlier (at NewServer time), and the other will eventually just be "waiting to
make sure we've joined the cluster". Right now it's calling Memberset.Open, and
then waiting …
> continue simplifying memberset and pilosa setup

- api.go
- http/translator_test.go
Fix TestTranslateStore_Reader tests. They were left non-working after refactoring to use `test.MustRunMainWithCluster`, so this gets them working again.
> Fix TestTranslateStore_Reader tests

- api.go
- ctl/import_test.go
- http/client_test.go
- server.go
- server/cluster_test.go
- test/pilosa.go
- test/pilosa_test.go
Builds on top of #1418 
Removes references to things like Server.Cluster and unexports them.
partially addresses #1247 
> Remove cluster refs

- Makefile
This excludes the Apache2 `LICENSE` file from the enterprise build directory for clarity.
I guess we should also make a build-specific readme that explains the license/build process more clearly, to package with the binaries. The current readme/notice kind of assume a source tree. Opinions welcome.
> Exclude Apache2 license from enterprise build directory

- api.go
- holder.go
- http/client.go
- http/error.go
- http/handler.go
- index.go
- index_test.go
- pilosa.go
- server/handler_test.go
This PR adds a custom `Error` to the `http` package which is used to return success true/false json responses.
TODO:
Fixes #1280
> consolidate http errors into a shared response type

- docs/administration.md
- http/client.go
- http/handler.go
- http/translator.go
- server/handler_test.go
This PR addresses the `internal` part of #1371.
The portion pertaining to import consolidation is a bit more involved, so I'm treating that separately.
> move internal http endpoints under /internal

- api.go
- apimethod_string.go
- http/client.go
- http/handler.go
This PR consolidates the `/import` and `/import-value` http endpoints into a single `/index/{index}/field/{field}/import` endpoint.
Fixes #1371
> consolidate import and import-value endpoints

- api.go
- cluster_internal_test.go
- executor_test.go
- field.go
- field_internal_test.go
- field_test.go
- fragment_internal_test.go
- holder.go
- holder_internal_test.go
- holder_test.go
- http/client_test.go
- http/handler.go
- index.go
- index_test.go
- server.go
- server/handler_test.go
- test/field.go
- test/holder.go
- test/index.go
- utils_internal_test.go
This PR ensures that functional options are used for any externally facing field creating method. With that complete, it was possible to un-export `FieldOptions` so that it's only used internally. The two commits represent those two steps.
> Un-export FieldOptions

- executor.go
- executor_test.go
- pql/ast.go
It seems we hadn't implemented `Set()` for integer fields (we were still relying on `SetValue(col=1, field=2)`). This PR adjusted the executor to handle the set based on field type.
> use Set() instead of SetValue() for integer fields

- api.go
- field.go
- holder.go
- http/handler.go
- index.go
This PR ensures that `views` are excluded from external calls to `/schema`.
It also adds the `keys` field option in schema output.
Fixes #1349
> ensure /schema excludes views and includes all field options (like "keys")

- gossip/gossip.go
- server/server.go
This PR renames `gossip.NewGossipMemberSet` to `gossip.NewMemberSet`.
It also removes the `gossip` from several internal names.
> rename gossip.NewGossipMemberSet to gossip.NewMemberSet

- http/handler.go
- server.go
- server/server.go
- test/pilosa.go
refactor handler Close func to use errgroup to be a bit less messy.
refactor pilosa.Server closing to actually return an underlying error if one occurs
add option to pilosa/test.Cluster and pilosa/server.Command to control close
timeout. currently is only used by the http handler, but conceivably could be
passed as a parameter to other subsystems of pilosa/server.Command
Fixes: pdk tests were hanging due to the soft shutdown w/o timeout in http handler.
> add a configurable timeout to http handler closing

- executor_test.go
- time.go
- time_internal_test.go
This PR adjusts the `viewsByTimeRange()` function to avoid date normalization problems in "YM" time quantum cases. 
Fixes #1436
> make sure time range views are calculated correctly across months

- fragment.go
- fragment_internal_test.go
- roaring/roaring.go
This PR adds methods `rows()` and `rowsForColumn()` to fragment. These are required by future work like group by and mutually exclusive fields. Most of this code was cherry-picked from #1496.
> Fragment rows() and rowsForColumn()

- holder.go
- http/handler_internal_test.go
- index.go
This adds IndexOptions to responses that serialize IndexInfo, including /schema, /index, and /index/{index}.
This came up during discussion on #1540.
> Add IndexOptions to IndexInfo json response

- holder.go
- server.go
When we removed `IndexOptions` earlier, we stubbed out the places it was being used with `IndexOptions{}`. This PR replaces two of those cases.
> fix places where empty IndexOptions were being used

- api.go
- client.go
- cmd/import.go
- ctl/import.go
- holder.go
- http/client.go
- http/client_test.go
- index.go
- test/pilosa.go
This pull request adds support for specifying string keys with `pilosa import`. There was an existing partial implementation but it did not work and required both the index and field to use string keys.
Keys are translated server-side so performance will be limited by the translation file speed. Previous tests show the speed to be quite high though.
Given an index `i`, a field `f`, and the following `data.csv` file: 
```
FOO,BAR
FOO,BAZ
```
The import can be run using the normal import command:
```sh
$ pilosa import -i i -f f data.csv
```
---
Fixes #1488
> Support keys on import CLI.

- docs/query-language.md
> fix topn spec and example in docs

- executor.go
- executor_test.go
- index.go
- pql/pql.peg
- pql/pql.peg.go
- pql/pqlpeg_test.go
- test/index.go
The parser was expecting an integer rowID on `SetRowAttrs()`.
This PR adds a `row` type to the parser which can handle integers or strings. The executor was updated to allow for the change in `Call` arguments.
Fixes #1554 
> update parser to handle row keys on SetRowAttrs()

- http/handler_internal_test.go
This fixes the following error we have been getting on Go master builds:
```
handler_internal_test.go:85: test 1: expected error: json: cannot unmarshal number into Go struct field postFieldRequest.options of type http.fieldOptions, but got result: json: cannot unmarshal number into Go value of type http.fieldOptions
```
> Use string prefix instead of equality so json error message will pass on all Go versions

- .travis.yml
- Makefile
Backport #1504 from master to v1.0
This will ensure that the v1.0 release branch produces automatic prerelease binaries in S3 bucket build.pilosa.com.
> Backport #1504

- api.go
- cluster.go
- cluster_internal_test.go
- ctl/server.go
- holder.go
- http/translator.go
- server.go
- server/config.go
- server/server.go
- translate.go
- translate_test.go
This PR moves `translateFile` from `Server` to `Holder`.
Additionally, it uses `cluster.Coordinator` as the primary translate store for key replication.
Replication to multiple nodes are daisy-chained across the cluster: 
```
node0 (coordinator) -> node1 -> node2
```
In that example, if `node1` is removed, the replication on `node2` will cleanly stop, change its primary translate store to be `node0`, and start replication again.
This PR also deprecates the `translation.primary-url` configuration option.
Note that a couple of items have been left in for API stability even though they are no longer used. Marked here as `DEPRECATED`.
Fixes #1578
TODO:
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but …
> Treat coordinator as primary translate store.

- api.go
- client.go
- ctl/import.go
- ctl/import_test.go
- encoding/proto/proto.go
- http/client.go
- http/client_test.go
This PR adds support for importing into integer fields with column keys.
There was a bug in protobuf decoding of `pilosa.Row` which is addressed here as well.
Fixes #1594 
> Import key values

- api.go
- client.go
- fragment.go
- holder.go
- holder_test.go
- http/client.go
- http/client_test.go
- http/handler.go
- test/holder.go
This PR addresses a bug in `fragmentSyncer` where it was always using the `standard` view when syncing. This was a problem with `time` fields which contain multiple views.
Fixes #1598 
> adds view parameter to sync logic for syncing time fields

- uri.go
- uri_internal_test.go
This change simply adds a check to make sure the port is valid.  Prior to this, any integer value was happily accepted (and a choice over 65,535 resulted in no error thrown).
> Require a valid port that isn't greater than 65,535

- api.go
- cluster.go
- cluster_internal_test.go
- executor.go
- holder.go
- holder_internal_test.go
- server.go
- server_internal_test.go
- utils_internal_test.go
Cluster resize stops any running anti entropy tasks before it can begin. Anti-entropy can't start running while cluster is in state RESIZING.
I wrote a few tests for this, but doing more thorough tests is quite difficult for these components. I started down the path of trying to stress test it (running lots of resizes over significant data while AE interval is set very low), but I think I've triggered some unrelated bugs.
See if you think it'd be acceptable to merge this without any additional tests for now, and I'll work on the stress tests at least in a separate PR.
Note that many of the changed lines are from renaming `cluster.nodes` - this came about due to a race condition in API.Nodes.
Fixes #1492 
This is the checklist that the reviewer will follow while reviewing your pull …
> Fix - prevent anti-entropy and cluster resize from running simultaneously

- translate.go
monitorReplication is now not allowed to return until the goroutine it starts
cancels the context. Previously, it could return just before the context was
canceled which caused a race between its internal goroutine and
handlePrimaryStoreEvent which recreates a channel which that internal goroutine
was listening on.
handlePrimaryStoreEvent already correctly made sure that monitorReplication had
returned before recreating the channel, so proper handling of the sub-goroutine
of monitorReplication was all that was needed to avoid this race.
Fixes #1606 
> fix race on replicationClosing channel

- client.go
- cmd/import.go
- ctl/import.go
- http/client.go
* I had to add `client.CreateFieldWithOptions` and `client.EnsureFieldWithOptions` functions in order to be able to pass create a field with options.
* `client.CreateFieldWithOptions` takes a `pilosa.FieldOptions` argument, but `http.postFieldRequest` requires the options as `http.fieldOptions`. Had to  convert from the former to the latter. I had to set different fields depending on the type of the field, since e.g., setting `Min` or `Max` is invalid for `set` fields (I'm happy that the tests cover that)
* I had to use `--index-keys` and `--field-keys` since `--index.keys` and `--field.keys` makes a few tests fail
* I didn't remove `--string-keys`. Should I ?
Fixes #1570
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything …
> Adds --field-keys and --index-keys options to pilosa import

- api.go
- executor.go
- executor_test.go
- pql/pqlpeg_test.go
Implements Query call excludeRowAttrs, excludeColumns, columnAttrs and shards args. I didn't remove the older http query argument code which sets those options in order to not break compatibility with Pilosa 1.x.
~TODO: columnAttrs arg. This requires adding attributes at the reduce stage `api.server.executor.Execute` or `api.Query` and as far as I see it would break compatibility with Pilosa 1.x Looking for a way that doesn't break compatibility. The alternative is matching `Query(..., columnAttrs=true)` at `api.Query` enable column attributes there which won't break the compatibility.~
Fixes #700
> Implements Query call and excludeRowAttrs, excludeColumns, columnAttrs and shards args

- apimethod_string.go
When `make generate` is run, the newer version of go is creating a different apimethod stringer. I just wanted to update that file so I don't keep changing the file on generate.
> re-generate the apimethod stringer

- api.go
- server/server_test.go
This addresses what I consider a bug in timestamp imports. See #1650 for a description.
Fixes #1650
> treat import timestamps as UTC

- cmd/server_test.go
- ctl/server.go
- docs/configuration.md
- holder.go
- server.go
- server/config.go
- server/server.go
- server/server_test.go
- test/pilosa.go
- translate.go
- translate_mapsize_386.go
- translate_mapsize_all64bitsystems.go
- translate_test.go
This adds a configuration flag for the translate map size. This configuration is used to lower the map size on 32-bit systems so the allocator should no longer fail in tests.
Fixes #1604
Fixes #1546 
> Make translate map size configurable

- api.go
- encoding/proto/proto.go
- server.go
This PR fixes a bug in the proto decoder caused by passing a zero-length slice and then modifying it (which doesn't modify the underlying array).
> fixes pass-by-value issue in proto decode

- field.go
- field_internal_test.go
- server.go
- server/server_test.go
This PR replaces the previous attempt (#1659) at making `remoteAvailableShards` immediately available after startup.
> store remoteAvailableShards to file

- enterprise/b/containers_btree.go
- roaring/containers.go
- roaring/roaring.go
- roaring/roaring_internal_test.go
Memory optimization
Fixes #825
** Before
Container.mapped bool: 0-1 (size 1, align 1)
Container.containerType byte: 1-2 (size 1, align 1)
padding: 2-8 (size 6, align 0)
Container.n int: 8-16 (size 8, align 8)
Container.array []uint16: 16-40 (size 24, align 8)
Container.bitmap []uint64: 40-64 (size 24, align 8)
Container.runs []github.com/pilosa/pilosa/roaring.interval16: 64-88 (size 24, align 8)
** After
Container.mapped bool: 0-1 (size 1, align 1)
Container.containerType byte: 1-2 (size 1, align 1)
padding: 2-4 (size 2, align 0)
Container.n int32: 4-8 (size 4, align 4)
Container.array []uint16: 8-32 (size 24, align 8)
Container.bitmap []uint64: 32-56 (size 24, align 8)
Container.runs []github.com/pilosa/pilosa/roaring.interval16: 56-80 (size 24, align 8)
> shrank n(container bit count cache) to int32

- server.go
- test/pilosa.go
- translate.go
Still getting a few intermittent memory allocation errors on 32-bit builds. This further decreases the map size to avoid those errors and also adds better error wrapping.
> Wrap translation store errors, decrease test map size to prevent failure on 32-bit

- api.go
- http/handler.go
- server/handler_test.go
Checks the field type on roaring import; if it's not a set field, returns an error.
Fixes #1660 
> Fixes #1660

- docs/query-language.md
- executor.go
- executor_test.go
- fragment.go
- fragment_internal_test.go
- pql/pql.peg
- pql/pql.peg.go
This PR implements `Store(<row_query>, <fieldname>=10)`. Currently, it's only supported on `set` fields. It's not clear to me yet how we would support this on `mutex` and `bool` fields. And I don't think it makes sense to store a `row` result into `int` or `time` fields (although I suppose if `Store()` took an optional timestamp, it could apply the row to all time quantums).
Also, the PQL function is `Store()`, but internally everything is `SetRow()` because it seemed like a complement to `ClearRow()`.
Fixes #637 (at least the first phase of it)
TODO:
> Store() function

- executor.go
- executor_test.go
This PR fixes a bug that prevented `Range()` queries from translating row keys.
Fixes #1678 
> ensure a Range() query with field keys is handled correctly

- api.go
- executor.go
- executor_test.go
- pilosa.go
> Fixes #1632

- server/server.go
When running tests with the `-v` verbose flag, `logOutput` was getting set to `os.Stderr`. In some test that used `test.command.Reopen()`, this was causing `os.Stderr` (or `/dev/stderr`) to be closed, which caused problems later.
This PR just prevents closing `logOutput` when it is `os.Stderr`
> prevent closing os.Stderr (used in verbose test logging)

- api.go
- client.go
- cmd/import.go
- cmd/import_test.go
- ctl/import.go
- ctl/import_test.go
- docs/administration.md
- field.go
- fragment.go
- fragment_internal_test.go
- http/client.go
- http/client_test.go
- http/handler.go
This PR adds functional options to all exposed Import-related api methods. Providing `OptImportOptionsClear(true)` to an `Import()` method will treat the payload as clear-bits.
Fixes #1657 
TODO:
> add `clear` functional option for imports

- http/handler.go
Long ago, the maintainers of gorilla/mux concluded that
it was a "wontfix" to return StatusMethodNotAllowed instead
of StatusNotFound for a method mismatch. Pilosa had a
workaround for this for the most common case (GET requests
to /index/{index}/query), and a TODO to address the other
cases.
While browsing the go-pilosa client code, I noticed that there
is a test for roaring import support which relies on getting
StatusMethodNotAllowed.  But how can this work, if gorilla/mux
doesn't do that?
Answer: They started doing it in mid-2017, apparently:
https://github.com/gorilla/mux/issues/271
Dropping this code changes the exact text of the message
produced for that one case, but not the status code,
and makes the behavior less confusing.
Remove superfluous code. No issue #. No doc change …
> Drop now-superfluous methodNotAllowedHandler

- pql/pql.peg
- pql/pql.peg.go
`uintrow` rule in the PEG grammar is not being used (I think it was an alternative to the `row` rule). A warning is generated about it when generating the Go code from the grammar. It doesn't affect anything, but @seebs noticed that that causes an "unused" error in staticcheck, so it's better to remove it.
Fixes #
> Removed unused rule from peg grammar

- translate_test.go
When running the translate file benchmarks, it's possible (and probable) for the benchmark to create more than 64MB worth of key data. When this happens, the benchmarks fail. This PR increases that file size to 128MB. Hopefully this doesn't put too much pressure when running tests which use this `NewTranslateFile()` function.
> increase the translate file size for tests/benchmarks

- fragment.go
- fragment_internal_test.go
data race on the checksums map in fragment.go	
Running with the race detector reveals several other data races that need to be addressed, but they aren't directly related to this.
Fixes #1746 
> fix fragment checksums race condition

- Makefile
This  removes redundant `require-X` code in the Makefile by utilizing the `%` magic char.
> Simplify "require-*" logic in Makefile

- .circleci/config.yml
This makes all builds default to Go 1.11 and adds the race detector to a parallel build pipeline. PRs will only depend on the non-race-detector build, allowing the race detector to finish in parallel with our workflow.
> CircleCI: Add race detector to parallel build. Default to Go 1.11.

- enterprise/b/containers_btree.go
- http/handler.go
- roaring/containers.go
- roaring/roaring.go
- roaring/roaring_internal_test.go
- roaring/roaring_test.go
This pull partially addresses #1765 by providing a much faster and less allocation heavy implementation of the union operation.
> Implement fast roaring bitmap union (Part 1)

- docs/query-language.md
previously was not rendering - I assume because it was being interpreted as an HTML tag.
minor docs fix
> wrap <CALL> in backquotes so it gets displayed.

- api.go
- fragment.go
- holder_test.go
Anti-entropy was sending (potentially) large batches of `Set()` and `Clear()` calls via PQL. This PR converts that logic to build a roaring bitmap and use the `ImportRoaring` api method instead.
> convert the anti-entropy logic to use `ImportRoaring` instead of `QueryNode`

- Makefile
- cluster.go
- gossip/gossip.go
- internal/clustertests/docker-compose-replication2.yml
running
"make clustertests
DOCKER_COMPOSE=internal/clustertests/docker-compose-replication2.yml"
shows this issue (just remove the change in cluster.go).
Also removed two unrelated lines of code that appear to be doing absolutely nothing.
Fixes #1776 
> fix bug where cluster goes into RESIZING instead of NORMAL

- fragment_internal_test.go
Adds a series of benchmarks for importing into fragments and then updating them
Fixes #
> Import benchmarking

- roaring/roaring.go
- roaring/roaring_test.go
This pull request fixes a bug in the new UnionInPlace function that was added recently. Note that the bug only affects the new API where the method is called with multiple values, and any existing code should still be fine.
The bug was introduced because one of my original assumptions was violated during refactoring I did as part of the P.R review process. To avoid this happening in the future, I added a "property" test that generates a bunch of random numbers/bitmaps and unions them together and compares to a reference implementation. This test would have caught the original issue and should make future refactors much safer.
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the …
> Fix bug in UnionInPlace function and add property test

- http/handler.go
suspect that this is somehow causing "cannot assign requested address" bugs for
some users. removing since it wasn't a necessary part of the deadlock fix, but
just seemed like a prudent thing to have.
> revert client Timeout addition

- api_test.go
- executor_test.go
- holder.go
- http/client_test.go
- pilosa.go
- pilosa_internal_test.go
use _exists for field name, and don't return _ fields in schema responses
Fixes #1691 
> 1691 existence namespace

- http/client.go
- pilosa.go
- server/server_test.go
I was reading about problems with the current net/http client in Go from this page: https://github.com/bradfitz/exp-httpclient/blob/master/problems.md
It talks about the necessity to always close the response body to avoid leaking connections and goroutines which got me thinking about an issue that was reported privately with errors like: "creating view: sending CreateView message: executing request: Post http://10.122.25.53:10101/internal/cluster/message: dial tcp 10.122.25.53:10101: connect: cannot assign requested address"
I looked through our client to see if we were forgetting to close any response bodies and found a few places. 
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of …
> Ensure internal client closes all response bodies

- executor.go
- row.go
- row_test.go
Optimization for group by. Skips results with count of 0 as early as possible. 
@benbjohnson added you since Todd and I both worked on this a bit, and you've been into this code semi-recently. If you could give it a once-over I'd appreciate it.
> Group by skip 0

- .github/ISSUE_TEMPLATE.md
Personally, I would prefer the erroneous behavior experienced due to a bug be the first thing described in the issue. This PR reverses the order of items in the issue template to support that. I'm not sure about what the labels should be, but here's a suggestion.
> reverse the order of items in the github issue template

- fragment_internal_test.go
The `f.Clean(t)` call was deleting the fragment data at the end of each benchmark. The problem arose when a benchmark needed to use `testdata/sample_view/0`, which is a static file checked into the repo and used for testing. Once this file was deleted, future benchmark runs trying to use the file would fail.
You may need to run 
```git checkout -- testdata/sample_view/0```
to restore your local test file before this fix will work.
Fixes #1791 
> don't delete test fragment data (part of repo)

- fragment_internal_test.go
This provides a simple benchmark that can be used for
setValue, to give a way to compare results from adding BSI
support to roaring. Use the BSIGroup prefix for the
fragments, and specify a cache type of "none", to prevent
the use of a LRU cache (which makes things more expensive).
Add a parallel benchmark for ImportValue, so we can compare
them. (Unsurprisingly, the bulk-import endpoint is quite a
lot faster.)
Also, add a test for clearing values to the TestFragment_Sum
test; it turns out that this was never tested in this code,
but the http client test would test it and verify it, it should
probably also be tested here.
A couple of holes in testing, and some benchmarking I wanted to have around when playing with the performance of SetValue.
This is the checklist that the reviewer will …
> setValue test and benchmark updates

- executor.go
- executor_test.go
This PR temporarily addresses the issue described in #1783 until an actual solution for that issue is available. 
> raise an error on Rows() query against a time field with noStandardView: true

- cluster.go
Just noticed this while working on something else, but didn't want to combine it with a separate PR.
I don't think `cluster.Nodes()` needs a write lock.
> cluster.Nodes() just needs a read lock

- ctl/server.go
- docs/configuration.md
- gossip/gossip.go
- http/client.go
- pilosa.go
- server/config.go
- server/config_internal_test.go
- server/server.go
- server/server_test.go
This PR adds support for advertise address by using a new config
option `advertise-addr`, or by defaulting its value to that
specified in `listen-addr`. Also replaces `bind` with `listen-addr`.
Also adds support for listening on 0.0.0.0 by trying to determine
the preferred outbound IP to use for the advertise address.
Fixes #1735
TODO:
> support advertise address and listen on 0.0.0.0

- field.go
This PR forces `cacheSize` to be `0` if `cacheType` is `none`.
Fixes #1702 
> set cache size to 0 if cache type is none

- executor_test.go
- pilosa.go
This PR fixes a bug that was introduced in #1677 with an `omitempty` json tag which would omit a valid zero value.
Fixes #1682 
> prevent omitting zero ids on columnattrs

- executor.go
- executor_test.go
This PR ensures that `ClearRow()` queries pass through the call translator.
Fixes #1847 
> ensure ClearRow() arguments get translated

- docs/query-language.md
- executor.go
- executor_test.go
- time.go
- time_internal_test.go
This PR adds `from` and `to` arguments to the `Rows()` call.
If the field specified is type `time`, then the `from` and `to`
can be used to restrict the results.
Fixes #1783
> add from/to range arguments to Rows() call

- api.go
- roaring/roaring.go
Due to the fact that pilosa roaring files do not mutate the internal bitmaps we can avoid a costly copy on import.   
Fixes #1850
> removed copy for pilosa roaring files

- NOTICE
- enterprise/enterprise.go
- fragment.go
- fragment_internal_test.go
- roaring/btree.go
- roaring/containers_btree.go
- roaring/roaring.go
- roaring/roaring_internal_test.go
- roaring/roaring_test.go
Fixes  #1864
For all imports except roaring imports, we build two slices of bitmap positions - one to set and one to clear. We reuse existing slice arguments when possible to avoid extra allocations.
After building these two slices, we call fragment.importPositions which decides whether or not this import should cause a snapshot or write the changed bits to the op log after applying them in-memory. This decision is based on the values of fragment.opN, fragment.MaxOpN, and the number of bits to be set and cleared.
Note: value imports don't use importPositions for the snapshotting path.
For bulkImportStandard, we no longer build a separate bitmap and Union it in. Instead we've created new roaring bitmap methods which are better optimized for bulk insertion. These methods keep track of the …
> 1864 random import perf

- cluster.go
- fragment.go
- fragment_internal_test.go
- server/config.go
Edit: didn't end up doing UnionInPlace because several benchmarks were absolutely mangled by the issue mentioned in the next paragraph. What we have done in this PR is added a "smallWrite" path to importRoaring that uses importPositions when the number of incoming bits is small. This either has no significant effect, or improves performance pretty much across the board. It's possible that for extremely large numbers of rows, it would slow things down a bit because we use a map instead of a slice to track the set of rows seen. This could be fixed quite trivially, but in a very ugly way by supporting either a slice or a map in importPositions, but I have in mind a better fix down the road where I think we can avoid tracking the rowSet at all.
Previous:
get the count of the existing fragment …
> smallWrite path for import-roaring

- fragment.go
- roaring/roaring.go
- roaring/roaring_internal_test.go
- roaring/roaring_test.go
UnionInPlace was making a lot of copies and/or new bitmaps to simplify the merge logic. The logic for just grabbing the one container for a key was slightly broken by late changes to the UnionInPlace PR to simplify/clean up the logic to treat the target as a method receiver, which made the SummaryStats computation of whether a container was the "only" container slightly wrong. Thus, in the case where the receiver had no container, but one of the things being merged in did, we were creating a new container and unioning everything into it -- even if there was only one evereything to union.
Cleaned that up, also stopped coercing everything to bitmap right away. We coerce to bitmap if we need to, but special-case array/array merges to allow them to stay arrays if N stays small.
Fixes #1875 …
> Address UnionInPlace performance regressions

- roaring/roaring.go
- roaring/roaring_internal_test.go
Want to make empty containers a thing of the past, but that can wait for another
day.
Fixes hanging go-pilosa integration tests.
I'm starting the "[no changelog]" convention for PRs which fix bugs which occur in code which is new since the last release and therefore don't affect the CHANGELOG.
> quick fix for Bitmap.Any bug [no changelog]

- ctl/server.go
- docs/configuration.md
- fragment.go
- fragment_internal_test.go
- server/config.go
- server/server.go
- syswrap/os.go
close files after using them if global max is passed.
I originally implemented this without the global count—just always closing files
when done with them, and reopening for new writes. This was crazy slow for that
one test that uses mustSetBits in a big loop. I modified the test to use
importRoaring and everything worked better (though still slower).
After adding the global counter, I ran the tests with that one test using
mustSetBits again, and the performance was similar to master. After completing
this PR, I ran the tests with the max limit set to 5—they still passed but were
much slower.
Fixes #1905 
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be …
> implement global open file counter using syswrap

- cmd/server_test.go
- ctl/server.go
- docs/configuration.md
- server/config.go
- server/server.go
set sane defaults. The performance overhead seems to be negligible, and this will allow us to obtain mutex and blocking profiles from running Pilosas by default.
Also see commentary here: https://github.com/pilosa/pilosa/pull/1877
> implement config options for block profile rate and mutex fraction

- api.go
- diagnostics.go
- gopsutil/systeminfo.go
- server/handler_test.go
report the approximate hardware specs (CPU speed, cores, memory)
of the server in the /info endpoint. This may be useful when
benchmarking.
Fixes #651
(note: docs haven't been changed, and maybe they should, but right now we don't actually document /info at all, apparently?)
> add server stats to /info endpoint

- Makefile
- fragment_internal_test.go
The benchmarks take an absurdly long time to run, and I think these are the
largest offenders. Dropping to two concurrency cases 2 and 16 should give a
pretty good idea.
The Makefile target will make things a bit easier to run from the infra repo—I just ran into an issue where `go test -bench` failed because go modules aren't enabled by default.
Fixes #
> run fewer concurrency level benchmarks, add bench Makefile target

- fragment.go
- fragment_internal_test.go
We accidentally used sliceContainers when we should have been using BTree containers in importRoaring. Coupled with the UnionInPlace change where we union into whichever bitmap has more containers, this caused an absolute massive slowdown in the case where the incoming bitmap had more containers, and the existing bits were all or mostly in containers which came before the incoming ones in the bitmap. 
This causes massive amounts of copying/and resizing in sliceContainers.
A benchmark is included that shows an instance of this. It's actually significantly less stark of a difference than what occurred with the taxi import which is where we first noticed this issue.
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this …
> fix importRoaring perf regression [no changelog]

- roaring/btree.go
- roaring/btree_test.go
- roaring/containers_btree.go
- roaring/inst.go
- roaring/nop_inst.go
Noticed in passing that a lot of the runtime of value-related stuff is living in the code that finds things in the btrees, and there were some old TODO comments that suggested possible opportunities. Also looked at upstream a bit, and ended up sending them a benchmark justifying our local change to the `overflow` function, then decided to migrate the tests from that package back into our tree so we can be testing the btree code more carefully.
Also adjusted the tuning parameters, and inlined the sense of the comparison that we were using a cmp function for, which turns out to make btree operations themselves 10-30% faster.
No documentation changes, this shouldn't be visible to users.
I probably need to rebase this to master, but I wanted to get the actual changes looked at. (The …
> btree updates

- fragment.go
- fragment_internal_test.go
included test demonstrates bug
I know we have some thoughts in the pipeline for a better approach to importValue, so I didn't try to do anything fancy here.
The map of column ids is only used on the smallwrite path, so hopefully is never large.
> importValue should only consider the last instance of a column id

- fragment.go
- fragment_internal_test.go
- roaring/roaring.go
Data loss was occuring after a cluster restart. The issue was during the
unmarshaling of the op log when multiple values had been written to the log. The
lines in question were like "changed = changed || b.DirectAdd(v)" in which the
DirectAdd would only be executed when changed was initially false, once it was
true, it would never be executed again.
Fixes #1922 
> fix data loss bug and robustify test

- roaring/roaring.go
I don't think there's any reason that applying a batch of operations can't take advantage of these methods. I think they were created slightly after the initial addition of the op log batch operations which is why they weren't there already.
> simply setting list of values with *N methods

- cluster.go
- server.go
- server/cluster_test.go
- server/server_test.go
- utils_internal_test.go
needed an unlocked version of sendsync for use within the cluster, so also
implemented that. Added a number of tests trying to reproduce the issue, but was
not able to. Not sure it's worth keeping the new tests.
Fixes #1919
> address race condition by getting cluster nodes with lock

- go.mod
- go.sum
fixes (hopefully) race condidtion which plagues our CI builds
I rebased seebs' fix onto the latest memberlist master.
> replace memberlist dep with patched fork

- http/handler.go
- server/handler_test.go
This adds the appropriate `Content-Type` header to query responses.
Fixes #1873
> Add correct content type to query responses. Fixes #1873

- http/handler.go
- index.go
- pilosa.go
- server/handler_test.go
also include the invalid name when erroring that a name is invalid.
Context: I was using imagine, and had misconfigured it so that it was generating invalid names for things. It was erroring out, but I had no idea which name was invalid or what is was.
> return orig error instead of cause in handler

- field.go
- holder.go
- index.go
- server.go
- server_internal_test.go
- view.go
it seems to have a bug where there is some race on cluster startup
which can cause it to think that the node doesn't own any shards.
Fixes #
> remove shard validation stuff

- docs/getting-started.md
- docs/query-language.md
- go.sum
- pilosa.go
This PR fixes the error message regex returns on field and index names with leading digits.
Fixes #1972 
> Fixed error message returned by regex on field and index names

- pql/ast.go
- pql/parser.go
- pql/pqlpeg_test.go
Fixes PQL to return error when int64 max is exceeded instead of panicking.
Fixes #1971 
> Fixed out of bounds panic to show error

- view.go
So it's true that Rename's arguments are called oldname/newname, and
you want to rename from the previous name to the new name.
And it's true that we're calling Rename on oldPath and newPath.
But in our case, oldPath is the name the fragment file had before
the operation, and newPath is the name of the temporary file
created during the operation.
> use os.Rename semantically correctly

- roaring/containers_slice.go
The "Update" case for Slice containers is broken, and can
insert a container without inserting a key. Fix this by using
the existing insert/add logic.
Silly bug, that I don't think was actually affecting us yet, because I don't think the Update function is actually being hit in current code paths, but it's still probably worth fixing.
Fixes #1991.
> handle insertions correctly

- roaring/fuzz_test.go
- roaring/roaring.go
When the readOffsets and readWithRuns functions are called, if the offsets within the official roaring bitmap aren't completely formed, then there will be a `slice out of bounds` panic. To fix this, a check is implemented to ensure that the bitmap is fully formed.
> Malformed Offset Bug in readOffsets and readWithRuns

- view.go
If you delete a fragment while something else is calling allFragments,
you can cause a race. This almost never happens in practice, because
deleting fragments is rare, and the only likely overlap would be with
something like the holder cache flush, which only happens once a
minute. But if you slowed down the rest of the tests enough, and ran
with -race, you might see it.
We check v.fragments directly instead of calling v.Fragment, because
v.Fragment also needs a lock, and we don't want to drop the lock between
the check for existence and the delete operation.
Fixes #2025
> view.deleteFragment should hold the lock while altering fragments

- field.go
- fragment.go
- fragment_internal_test.go
- holder.go
- index.go
- roaring/btree.go
- roaring/containers_btree.go
- roaring/containers_slice.go
- roaring/fuzz_test.go
- roaring/roaring.go
- view.go
Various roaring/unmarshalling/memory-mapping/etc stuff.
This is an attempt to address a series of issues related to the performance of importRoaring.
In no particular order:
* We allow roaring import as Add and Remove operations in the ops log. This lets us write many more bits of ops log much more quickly.
* We use that import/export functionality also to implement importRoaring itself. In the process, we get rid of the CountRange things used to rebuild the cache, since we can determine the number of bits added or removed from a row nearly as cheaply as we can determine whether or not any bits changed.
* When reopening storage, instead of unmarshalling a new bitmap and ditching all the existing containers, we iterate through updating the pointers of containers that match the …
> Unmarshal3

- cmd/server.go
- ctl/server.go
- docs/configuration.md
Have found some potential performance or stability issues associated
with lots of mutex blocking in getting a parent span's context. Want
the ability to totally disable tracing to help debugging.
Fixes #
> add ability to disable tracing and use nopTracer

- docs/getting-started.md
This will redo the current Getting Started on the Pilosa website. It is adding Go, Java, and Python and removing Docker.
> Getting Started Update

- encoding/proto/proto.go
Protobuf encodes/decodes `pilosa.Pair` type results.
Fixes #2031 
> fixes #2031

- executor.go
- holder.go
- server.go
- server/config.go
- server/server.go
- test/pilosa.go
add worker pool to executor for local query processing
Pilosa previously spawned a goroutine for each remote node that a
query needed to be forwarded to, and then forwarded a single request
containing all the shards that the query should operate on. It then
spawned a goroutine *per local shard* to process the query
locally. This was fine if there weren't too many shards, or too many
queries coming in concurrently, but we found that it created issues
when there were 100s or 1000s of shards per node, and dozens of
queries arriving concurrently.
Specifically, the memberlist "hiccup" issue is highly correlated with
many goroutine scenarios, and after applying this patch, memberlist
complaints in the logs were much decreased, and nodeLeave events under
concurrent query load almost entirely …
> Worker pool

- api.go
- server/config.go
- server/server.go
This PR adds a worker pool to handle `importRoaring` jobs.
I'm not sure if having this as part of `API` is correct. Because `API` isn't really thought of as a running object (and doesn't have anything like `close()`) there may be a problem with closing this out while jobs are in flight.
Fixes #2047 
> Add a worker pool for importRoaring jobs

- field.go
- field_internal_test.go
The BSI base value determined by `FieldOptions.Base` was defaulting to 0 (except in cases of migration from v1 of BSI). This PR changes the logic to set the `base` to either min, max, or 0 depending on the range of min/max.
Fixes #2013 
> Default BSI base value to min, max, or 0 depending on the min/max range

- cmd/root.go
- cmd/server.go
- ctl/check_test.go
- ctl/inspect_test.go
- field.go
- fragment.go
- index.go
- roaring/fuzz_test.go
- roaring/roaring.go
- roaring/roaring_internal_test.go
- roaring/unmarshal_binary.go
- server.go
- server/server.go
- view.go
What if startup loading of fields and views and fragments were parallel? Also, what if we used the shiny new roaring iterator used by ImportRoaring and the remap feature for initial roaring imports?
There's some opportunities for further enhancements here by custom-hacking the btree implementation to perform better in the case where every newly inserted key is sequentially greater than the highest previous key, but it's probably not worth the effort.
> WIP: address some startup speed and performance issues

- .circleci/config.yml
- field.go
- index.go
- roaring/btree.go
- roaring/nop_inst.go
- translate.go
- view.go
break in a select in a for terminates the current case of the
select, but does not terminate the for loop. The worker queue
implementations for opening indexes/fields/views all suffered
from the same issue here.
Also fix a `<= 0` on a uint value.
All hail staticcheck.
> use labeled targets for break statements

- fragment.go
- holder_test.go
- roaring/roaring.go
This is a revised version of jaffee's previous pull, it adds the actual code to do the reopen after truncating, and also a test case to verify that it seems to work.
> Truncate bad ops logs

- fragment.go
- roaring/roaring.go
Needs testing. I tested this manually by appending a small amount of data to an existing fragment file and then starting Pilosa. Pilosa was able to start normally and truncated the file to the correct location.
> truncate corrupt ops logs

- fragment.go
I am impressed that we missed this.
The reason this didn't cause weirder and earlier failures is that `errors.Wrapf` is getting the nil `terr` as its first argument, and thus returning a nil. We wanted to check the inner error, which got a distinct name because we want to keep the other error variable to report the original problem.
> fix typo in error check

- field.go
- fragment.go
- fragment_internal_test.go
- http/client_test.go
It seems that `fragment.importValue` doesn't clear `fragment.rowCache` the way that other mutating methods do (see: `fragment.importRoaring`, `fragment.unprotectedSetBit`, etc.).
This PR is pretty heavy-handed in that it clears the rowCache for all rows of the BSI value, as well as the existence and sign rows. There's likely a more elegant way to handle this, but I'm putting this here to get get feedback.
TODO:
Fixes #2083 
> Add logic that clears fragment.rowCache after importValue

- holder.go
- holder_test.go
This pR simplifies Holder's logic for `CreateIndex` like functions.
> Simplify Holder's logic

- executor_test.go
An extra test to check if _column existency bit_ is still set after `Clear` operation.
> Add extra Clear test (check if existency column bit is set)

- roaring/roaring.go
- roaring/roaring_internal_test.go
- roaring/roaring_test.go
When the interval is a proper superset of the range with start equal to
interval start, the range must be considered a superset or it will be
completly ignored (since it neither a subset nor it overlaps)
CountRange(start, end) may return 0 even if the bitmap contains bits in the range start and end.
See added unittest, especially:
```
bm3 := roaring.NewFileBitmap(1, 2, 3, 4)
bm3.Optimize() // convert to runs
if n := bm3.CountRange(1, 3); n != 2 {
t.Fatalf("unexpected n: %d", n)
}
```
> Fix offset-by-1 in CountRange with continuous bits interval

- field.go
- field_internal_test.go
There was an edge case where setting cacheType to none
wouldn't zero out its cacheSize. This fixes that edge case.
> Fix cacheSize when cacheType is none (and cacheSize is 0)

- cluster.go
If there is a resizing job, then we can return early without recaculating resizing job.
Fixes #
> 1. modify unprotectedGenerateResizeJob to return early iif resizing job

- holder.go
- Remove the `h.hasV1TranslateKeysFile`, because it's not correct.
>  holder.go: fix some logic errors

- executor.go
If you have two criteria, and the last result you generate is
empty, the nextAtIdx iterator for i==1 will try to continue
poking the i==0 iterator. That one produces a nil result, and
declares the entire group-by iterator done... But the nextAtIdx
call above it isn't checking that, and just loops forever.
This causes some queries to become stuck permanently, consuming
ridiculous amounts of resources almost entirely focused on
calling Intersect millions of times to get empty results.
> GroupBy should terminate even if the last result is empty

- fragment.go
- holder_test.go
In the case where a block merge needed to occur
on a replica containing a row on the edge of the block,
the existing logic would inadvertently clear the first
row in the next block. This PR fixes that.
> Fix off-by-one maxRowID in block limits

- roaring/roaring.go
- roaring/roaring_internal_test.go
Improve memory usage on union of run containers. It does not allocate a new slice.
If it's necessary it prepends/inserts intervals to the first container, otherwise it builds the longest interval in memory and set it on the right position.
Also it tries to optimize run's intervals by combining neighbours, e.g.
a := []interval16{interval16{1, 1}, interval16{3, 3}, interval16{5, 5}}
b := []interval16{interval16{0, 0}, interval16{2, 2}, interval16{4, 4}}
gives a []interval16{{0, 5}}
> Add unionRunRunInPlace

- executor.go
fixd: interface {} is nil, not bool
Fixes #
PANIC: interface conversion: interface {} is nil, not bool
pilosa    | goroutine 702717 [running]:
pilosa    | runtime/debug.Stack(0xc6f0bcefc0, 0x1f4, 0xc5f84a35c0)
pilosa    |     /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
pilosa    | github.com/pilosa/pilosa/http.(*Handler).ServeHTTP.func1(0xf53740, 0xc6f0bcefc0, 0xc0000fd2c0)
pilosa    |     /go/pilosa/http/handler.go:327 +0x96
pilosa    | panic(0xd536c0, 0xc5f84a35c0)
pilosa    |     /usr/local/go/src/runtime/panic.go:969 +0x175
pilosa    | github.com/pilosa/pilosa.(*executor).executeSetRow(0xc0003dd500, 0xf56d00, 0xc4ccf23a70, 0xc6efe27b6c, 0x4, 0xc4ccf23800, 0xc570978800, 0x7b, 0x80, 0xca8ff7d718, ...)
pilosa    |     /go/pilosa/executor.go:2011 +0x425
pilosa    | …
> fixd: interface {} is nil, not bool

- executor.go
This is a back-port of the fix from #2136 (`v1.4`) to `master`.
> fix interface{} -> bool err

- server.go
fixd: concurrent map iteration and map write
Fixes #
pilosa | fatal error: concurrent map iteration and map write
pilosa |
pilosa | goroutine 3873332 [running]:
pilosa | runtime.throw(0xe6062c, 0x26)
pilosa | /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc322b19080 sp=0xc322b19050 pc=0x437732
pilosa | runtime.mapiternext(0xc322b19168)
pilosa | /usr/local/go/src/runtime/map.go:853 +0x554 fp=0xc322b19100 sp=0xc322b19080 pc=0x410cf4
pilosa | github.com/pilosa/pilosa.(*Index).AvailableShards(0xc00023a320, 0x0)
pilosa | /go/pilosa/index.go:276 +0x1bf fp=0xc322b191e8 sp=0xc322b19100 pc=0x95d73f
pilosa | github.com/pilosa/pilosa.(*executor).execute(0xc0003ea600, 0xf56d00, 0xc7b9c285a0, 0xc73cbe0acc, 0x4, 0xc479cd1410, 0x0, 0x0, 0x0, 0xc361c69388, ...)
pilosa | /go/pilosa/executor.go:249 …
> fixd: concurrent map iteration and map write

- executor.go
the field is keys,store error
Fixes #
POST {{addr}}/index/{{schema}}/field/tmp
{"options": {"type": "set","keys":true}}
POST {{addr}}/index/{{schema}}/quer
Store(Row(fieldA=1), tmp='a')
Return: 
{
"error": "executing: mapReduce result is not bool,err:reading Store() row: could not convert a of type string to uint64 in Call.UintArg: reading Store() row: could not convert a of type string to uint64 in Call.UintArg"
}
> fixed store error in keys field

- cli/cli.go
When we added a line feed to the user input, we broke the check for "exit" (because after that change we were getting "exit\n". This commit moves the exit check before the line feed append.
> Fix CLI "exit" command

- .github/workflows/ci.yml
These tests are happening in GitLab CI instead.
> Stop go test in GitHub CI

- systemlayer/executionrequests.go
This PR caps the number of sql requests stored in memory and caps the amount of memory used to store sql test and plan text.
> get fb_exec_requests underlying storage to use less memory

- sql3/parser/ast.go
- sql3/planner/compileselect.go
- sql3/planner/opnestedloops.go
- sql3/planner/planoptimizer.go
- sql3/test/defs/defs.go
- sql3/test/defs/defs_join.go
- sql3/test/defs/defs_timequantum.go
This PR handles the comma case of inner join as well as a subquery as a source.  It also correctly handles the case of a nested loops operator not having a join expression in the optimizer.
> handle comma syntax of inner join

- sql3/planner/opbulkinsert.go
- sql3/planner/oppqlaggregate.go
- sql3/sql_test.go
- sql3/test/defs/defs.go
- sql3/test/defs/defs_aggregate.go
- sql3/test/defs/defs_bulkinsert.go
This PR fixes:
1. string representations of timestamps in CSV files now ingest the timestamp, and not 0 as it was previously
2. min and max on timestamps (where these are pushed down into PQL min/max operators
The requisite testing has been added.
> timestamp fixes

- systemlayer/executionrequests.go
this seems to work to stop all those persistent allocations we were seeing. There are two main things here:
1. When truncating SQL and SQL plan strings for storage, copy them to new fixed size memory allocations so we don't retain the entire underlying allocation.
2. make the requestsList a true ring buffer rather than tacking onto the end and reslicing off the beginning... I believe this was also retaining the underly memory allocation
> try to make sure we're releasing large allocations

- arrow.go
- cmd/parquet-info.go
- cmd/root.go
- ctl/parquet-info.go
provide a simple featurebase command to be able to inspect parquet files, it looks something like. this
```
❯ featurebase parquet-info ../data.parquet
Name:../data.parquet
0. Name: vendor_id
0. Type: utf8
0. Nullable: true
1. Name: pickup_at
1. Type: timestamp[us, tz=UTC]
1. Nullable: true
2. Name: dropoff_at
2. Type: timestamp[us, tz=UTC]
2. Nullable: true
3. Name: passenger_count
3. Type: int8
3. Nullable: true
4. Name: trip_distance
4. Type: float32
4. Nullable: true
5. Name: pickup_longitude
5. Type: float32
5. Nullable: true
6. Name: pickup_latitude
6. Type: float32
6. Nullable: true
7. Name: rate_code_id
7. Type: null
7. Nullable: true
8. Name: store_and_fwd_flag
8. Type: utf8
8. Nullable: true
9. Name: dropoff_longitude
9. Type: float32
9. Nullable: true
10. Name: dropoff_latitude …
```
> parquet-info command to browse parquet files

- dax/computer/service/computer.go
- dax/controller/controller.go
- dax/controller/node_registerer.go
- dax/controller/service/controller.go
- dax/controller/snapping_turtle.go
- dax/queryer/service/queryer.go
- dax/server/config.go
- dax/server/server.go
- dax/service_manager.go
- diagnostics_internal_test.go
- idk/header_test.go
- idk/kafka/source_test.go
- idk/kinesis/logger.go
- idk/kinesis/logger_test.go
- logger/logger.go
- server/config.go
- server/server.go
- server/server_test.go
make overall logs less verbose and chatty
1 minute computer check-in interval
3 minute snapshot interval
remove CaptureLogger as it has same functionality as buffer logger
add a WithPrefix to the Logger interface so sub-services can have different prefixes
> tweak a bunch of logging and config

- .gitignore
- sql3/test/defs/defs.go
- sql3/test/defs/defs_inserts.go
This PR adds a test for inserts with timestamp columns that have time unit and epoch constraints.
> (fb-1951) added test for inserts with timestamp + constraints

- sql3/planner/opbulkinsert.go
- sql3/sql_complex_test.go
This PR handle changes `BULK INSERT` to handle empty strings as `null` for CSV (except for `string` types).
> (fb-1970) CSV Empty String handling

- http_handler.go
- sql3/planner/executionplanner.go
This PR fixes an issue with header-based routing in the `http_handler` not working on a real cluster. The fix is to route by....well, route.
> (fb-1903) - Fix SQL Fanout error

- sql3/planner/expression.go
- sql3/planner/expressionanalyzercall.go
- sql3/planner/inbuiltfunctionsstring.go
- sql3/test/defs/defs_string_functions.go
STR() takes in a number and provides a string representation of it
first optional int variable will set a length to pad out to or to fill out with *'s if the number cannot be represented in that space (default 10)
Second optional variable will allow you to set the desired precision (default 0)
> FB-1862: Implement Str() scalar string function

- README.md
updated links for upcoming docs migration on 2/14/23. Please slack greg before merging in
> docs migration link changes

- sql3/planner/planoptimizer.go
This PR fixes a performance regression with the calculation of aggregates on ID/STRING types.
Currently, count(*) explicitly references the _id column and a recent change to allow non-pql aggregates on ID & STRING types did not take this into account.
This change will short circuit this check to force counts on _id columns to be executed using pql.Call.
> (fb-1978) - performance regression

- sql3/planner/expressionagg.go
- sql3/planner/expressionanalyzercall.go
- sql3/planner/expressiontypes.go
- sql3/planner/oppqlaggregate.go
- sql3/planner/oppqlgroupby.go
- sql3/planner/oppqlmultigroupby.go
- sql3/planner/opsystemtable.go
- sql3/planner/planoptimizer.go
- sql3/planner/types/planexpression.go
- sql3/sql_complex_test.go
- sql3/sql_test.go
- sql3/test/defs/defs.go
- sql3/test/defs/defs_aggregate.go
- sql3/test/defs/types.go
- sql3/test/helpers.go
This PR refactors aggregation an adds the ability to aggregate on expressions and not just references.
- Removed `AGGREGATE_ILLEGAL` thru `AGGREGATE_MAX` enum constants and associated stuff in `Aggregable` since each aggregate has it's own type and we can use that instead of the enum (fb-1658)
- Refactored `Aggregable` to be clearer  - replacing `AggExpression()` with `FirstChildExpr()` and `AggAdditionalExpr()` with `Children()`. For aggregation functions, this makes the simple 1 argument case more explicit and the multiple argument case easier.
- Enabled expressions to be used as aggregate terms for `sum()`, `avg()`, `min()` and `max()`
- Ensured that we do the right thing for `_id` columns if these are used as terms
- Simplified optimizer handling for aggregates
- This PR also fixes …
> Aggregation Nation (fb-1955, fb-1887) 

- sql3/planner/compilealtertable.go
- sql3/planner/compilebulkinsert.go
- sql3/planner/compilecreatetable.go
- sql3/planner/compileinsert.go
- sql3/planner/compileselect.go
- sql3/planner/compileshow.go
- sql3/planner/expression.go
- sql3/planner/expressionagg.go
- sql3/planner/expressionanalyzercall.go
- sql3/planner/expressionpql.go
- sql3/planner/expressiontypes.go
- sql3/planner/inbuiltfunctionstable.go
- sql3/planner/opcreatetable.go
- sql3/planner/opfeaturebasecolumns.go
- sql3/planner/opfeaturebasedatabases.go
- sql3/planner/opfeaturebasetables.go
- sql3/planner/opinsert.go
- sql3/planner/oppqlaggregate.go
- sql3/planner/oppqldelete.go
- sql3/planner/oppqldistinctscan.go
- sql3/planner/oppqlgroupby.go
- sql3/planner/oppqltablescan.go
- sql3/planner/planoptimizer.go
- sql3/planner/systemobjects.go
- sql3/test/defs/defs.go
This PR alters the behavior of `count(*)` to not depend on the `_id` column until the optimizer is sure that the operation is going to end up in a `pql.Call` graph.
This PR also replaces relevant instances of `"_id"` with he appropriate constant.
> Make count(*) not depend on _id (fb-1974)

- sql3/errors.go
- sql3/planner/expression.go
- sql3/planner/expressiontypes.go
- sql3/planner/opinsert.go
- sql3/test/defs/defs_date_functions.go
- sql3/test/defs/defs_timequantum.go
This PR adds support for time quantum inserts with explicit timestamps.
Oh, and tests.
> add support for time quantum inserts with explicit timestamps (fb-1558)

- sql3/planner/compileselect.go
- sql3/planner/expression.go
- sql3/planner/expressionanalyzer.go
- sql3/planner/expressiontypes.go
- sql3/planner/inbuiltfunctionstable.go
- sql3/planner/oporderby.go
- sql3/planner/planoptimizer.go
- sql3/test/defs/defs_orderby.go
This PR handles the case of a term appearing in the  ORDER BY clause for a term not in the projection list for a SELECT.
Additional compiler behavior has been changed thus:
1. The compiler will now place the PlanOpOrderBy op before the PlanOpProjection op for in cases where there are only references  in the order by expression list (or positional expressions that can be resolved to references.
2. The compiler will also handle the case of a reference appearing in the order by expression list that is not projected.
3. If the order by list contains non reference expressions and references that do not appear in the projection list, the compiler will: a) generate a new projection containing the original projection's schema, b) make the order by operator a child of that projection op and c) …
> ORDER BY ....what now!? (fb-1954)

- Makefile
This PR fixes a bad FLAGS value (-o featurebase) passed when building for the packaging target.
> Fix bad FLAGS env var passed when building to package.

- .gitlab/.gitlab-ci.yml
- Makefile
- translate.go
So, we were special-casing creating a ramdisk, and setting a special environment variable for it, for boltdb translate files, to improve performance.
But actually, etcd and test cluster data and so on all go in $TMPDIR, and if you move all of those also into a ram disk, you get way better performance. But 2GB may not be enough for that.
So!
We unify on $TMPDIR, we bump the default size to 4GB, we make the size configurable, and we stop using the name RAMDISK. This should improve performance on MacOS significantly for `make test` and things like it, and also simplifies our lives by not having a special case for the boltdb translate files.
> improve ramdisk config in Makefile, use it for everything in tests

- .gitlab/.gitlab-ci.yml
- Makefile
Using the same build target was problematic because they shared the same flags. Since the `-o` output flag was used, the fbsql binary was overwriting the featurebase binary.
> Separate the featurebase and fbsql make build targets

- dax/table.go
- dax/table_test.go
- sql3/parser/ast_test.go
- sql3/parser/parser.go
- sql3/planner/expression.go
- sql3/planner/expressionanalyzercall.go
- sql3/planner/expressiontypes.go
- sql3/planner/inbuiltfunctionsdate.go
- sql3/planner/opbulkinsert.go
- sql3/planner/opinsert.go
- sql3/sql_complex_test.go
- sql3/test/defs/defs_date_functions.go
- sql3/test/defs/defs_inserts.go
- sql3/test/defs/defs_timestamp_literals.go
- Remove EPOCH column constraint from TIMESTAMP data type in SQL DDL
- Support implicit conversion of int to timestamp in SQL, treat the integer value as seconds from unix epoch.
- Add new scalar SQL function ToTimestamp(num, timeunit) to help convert integers values to Timestamp at user specified granular input.
> Fb 1968 timestamp data type related fixes and enhancements

- dax/test/dax/dax_test.go
- sql3/parser/parser_test.go
- sql3/planner/opfeaturebasecolumns.go
- sql3/sql_test.go
- sql3/test/defs/defs.go
- sql3/test/defs/defs_filterpredicates.go
- sql3/test/defs/defs_join.go
- sql3/test/defs/defs_sql1.go
- sql3/test/defs/types.go
This forward-ports a number of tests from the previous SQL implementation. The porting is approximate in a number of ways, and not all tests are implemented/tested yet.
In particular, several tests are currently disabled because we don't support `limit n` constructs.
The tests that were primarily tests of the parser have been brought forward as parser tests. One of them has been altered to add parentheses, because our parser interprets
`fld1 between 1 and 3 and fld2 = 2`
as:
`fld1 between (1 and 3) and (fld2 = 2)`
which is invalid, while the old parser apparently interpreted it as:
`(fld1 between 1 and 3) and (fld2 = 2)`
We have not yet verified the SQL spec's requirements here, but sqlite agrees with our old parser, not our new parser, so this may be a regression.
The old tests expected …
> forward-port tests from SQL1 tree

- ctl/server.go
- http_handler.go
- http_handler_test.go
- server/config.go
- server/server.go
Default config will have the sq.endpoint-enabled set to true. Server instances started with default config will accept SQL requests.
> fb-2013 remove sql endpoint feature flag.

- cmd/server.go
- ctl/server.go
This uses the cobra library options to mark the sql3 flag as deprecated so the DB doesn't, ya know, explodey if someone tries to pass it in after we remove the flag.
> This changes the server sub-command to ignore unknown flag. Fixes FB-2019

- sql3/planner/expression.go
- sql3/planner/expressionagg.go
- sql3/planner/oppqlgroupby.go
- sql3/planner/planoptimizer.go
- sql3/test/defs/defs_having.go
After tracking through a whole bunch of unrelated code and coming up with a 40-line patch that mostly fixed this, I realized that the fact that it worked for count(field) meant something was making it work, added `countStarPlanExpression` to that case, and magically everything got better.
Writing one line of code: 30 seconds
Figuring out which one line of code to write: two days
> handle count(*) in `having` correctly

- sql3/planner/expression.go
- sql3/planner/expressionanalyzercall.go
- sql3/planner/inbuiltfunctionsdate.go
- sql3/test/defs/defs.go
- sql3/test/defs/defs_date_functions.go
- sql3/test/defs/types.go
This new scalar SQL function adds the specified time duration to the target date-time and returns a new date-time.
> fb-1893 Adding new scalar SQL function datetimeAdd(timeunit, duration, target)

- cli/cli.go
Until we have API token support, connecting to cloud requires the cognito configuration. This commit adds the production cognito settings for defaults, and we have intentinally omitted these from the documentation.
> Add default fbsql cloud configuration

- sql3/planner/oppqlaggregate.go
- sql3/test/defs/defs_aggregate.go
AVG() returns null (as opposed to a very large magnitude value) when no records are returned by the WHERE filter.
> handle empty avg agg

- cli/Makefile
- cli/cli.go
- cli/cli_integration_test.go
- cli/cli_test.go
- cli/kafka.go
- cli/meta.go
- cli/splitter.go
- cli/testdata/database
- cli/testdata/famous.csv
- cli/testdata/meta_bang
- cli/testdata/meta_cd
- cli/testdata/meta_echo
- cli/testdata/meta_file
- cli/testdata/meta_include
- cli/testdata/meta_output
- cli/testdata/meta_pset_border
- cli/testdata/meta_pset_expanded
- cli/testdata/meta_pset_tuples_only
- cli/testdata/meta_set
- cli/testdata/meta_timing
- cli/testdata/meta_write
- cli/testdata/people.sql
- cli/testdata/query_buffer
- cli/testdata/setup
- cli/testdata/table
- cli/writer.go
Introduce fbsql integration test framework.
This also adds support for `pset location` to set the geo location (i.e.
time zone) in which timestamps should be displayed. And it adds support
for comments (lines starting with `--`) in the line reader/splitter.
> fbsql integration test framework

- cli/cli.go
- cli/cli_integration_test.go
- cli/meta.go
- cli/testdata/meta_pset_format_csv
- cli/testdata/meta_timing
- cli/testdata/setup
- cli/testdata/table
- cli/writer.go
- cli/writer_test.go
This adds the `\pset format csv` meta command support.
> Add CSV support to fbsql

- .golangci.yml
- bufferpool/page.go
- ctl/dataframe-csv-loader.go
- ctl/keygen.go
- ctl/restore_tar.go
- dax/queryer/orchestrator.go
- etcd/embed.go
- http_translator.go
- idk/datagen/cmd.go
- idk/datagen/custom.go
- idk/idallocator.go
- idk/kafka/cmd_test.go
- idk/kafka/putsource.go
- idk/kafka/source.go
- metrics.go
- pql/ast.go
- roaring/filter.go
- sql/extract.go
- sql/model.go
- sql3/parser/walk.go
- sql3/planner/planoptimizer.go
- sql3/planner/planwalker.go
- sql3/planner/types/planexpression.go
- test/pilosa.go
- testhook/auditor.go
- testhook/registry.go
- vprint/vprint.go
This enables the stylecheck linter, but excludes some staticchecks for now. The following are ignored because they will take a bit of time to address, but the intention is to address them and remove them from the exclusion list.
ST1000: at least one file in a package should have a package comment
ST1003: golang naming standards
ST1016: methods on the same type should have the same receiver name
ST1020: comment on exported function
> Enable linter: stylecheck

- sql3/planner/opbulkinsert.go
- sql3/sql_complex_test.go
*  fieldtype idset with a number 
* fieldtype stringset with a string
* fieldtype Bool with a bool(true/false)
> Add SQL3 Tests added bulk insert tests

- sql3/test/defs/defs_groupby.go
FB-2027
The DataTypeIDSet and default branches in groupByColumns weren't getting tested. Added tests to make sure they are now covered.
> Add SQL3 test for oppqlgroupby.go

- sql3/test/defs/defs_string_functions.go
Things to document - 
`ASCII()` limit of [0, 127]
`CHAR()` limit of [0, 255]
We use UTC-8
`CHARINDEX()` returns `-1` when substring isn't found
> Add SQL3 tests - /planner/inbuiltfunctionsstring.go

- cli/cli.go
- cli/testdata/database
This adds the ability to disconnect from the current database by passing a hyphen to the `\c` meta-command.
> fbsql disconnect from database with `\c -`

- cli/cli_integration_test.go
- cli/meta.go
- cli/testdata/meta_describe
`\d` will list tables (in the future it will also include things like views)
`\d tablename` will show info about tablename
> fbsql: add support for `\d` meta-command.

- dax/test/dax/dax_test.go
- sql3/planner/expression.go
- sql3/planner/inbuiltfunctionsset.go
- sql3/test/defs/defs.go
- sql3/test/defs/defs_set_functions.go
- sql3/test/defs/defs_timequantum.go
FB-2041
Added tests for typeIsTimeQuantum and typeIsSet and made them pass. 
Added tests for DataTypeTuple cases in typesAreAssignmentCompatible. 
Timestamp conversion checking is handled before it gets to that point but I left those branches in as a backstop.
Checking to see if DataType[String,ID]SetQuantum can be assigned to themselves doesn't appear to be reachable currently but left those branches in, because something may use them in future.
> Add tests cases for coverage in expressiontypes.go

- sql3/planner/expression.go
- sql3/planner/expression_it_test.go
- sql3/planner/expression_test.go
- sql3/planner/expressionpql.go
- sql3/planner/opinsert.go
- sql3/test/defs/defs.go
- sql3/test/defs/defs_binops.go
- sql3/test/defs/defs_select.go
* Push down between operator 
[x] complete coerceValue coverage
[x] casePlanExpression->Evaluate, doesn't seem to be checking some of the cases in the baseExpr == nil case?
[x] plusWithTypeCheck->DataTypeID
[x] minusWithTypeCheck->DataTypeID
[x] compileExpr -> TupleLiteralExpr
[x] exprTupleLiteralPlanExpression->Evaluate 
[x] exprTupleLiteralPlanExpression->Plan, Children, WithChildren
[x] timestampFromString -> formats other than RFC3339Nano
[x  ]compileBinaryExpr -> parser.MINUS, SLASH, REM, and default
> SQL3 Test Coverage: complete coerceValue coverage

- .gitlab/.gitlab-ci.yml
- idk/Makefile
- idk/docker-compose.yml
- idk/ingest_test.go
After a weird CI failure that suddenly went away, I have theorized that we're getting cached versions of the featurebase docker image in CI when we don't intend to, and thus, running IDK tests against *the wrong version of featurebase*. This checks for that problem.
> make IDK check featurebase version

- sql3/parser/ast.go
- sql3/parser/parser.go
- sql3/parser/parser_test.go
- sql3/parser/scanner.go
- sql3/parser/scanner_test.go
This is actually two related sets of test cases in the parser/scanner stuff. (tickets 2073, 2074)
There's a couple of things in here which may want more careful attention. One is the previously-commented-out test case for a double inner join. It was commented out because stringizing the resulting data structure produced wildly different output, which broke the basic sanity checks. After studying this a bit, I've concluded that the code to "rewrite last source to nest next join on right side" logic was, in fact, precisely backwards -- we simply didn't want that code at all. Taking it out and expecting a data structure that makes sense also produces a data structure which stringizes back to the original query.
We add support for StringLit to know whether they came from blobs or not, so they …
> SQL test backfilling

- Makefile
account ID is based off the AWS_PROFILE currently set in the environment
> update ECR-related Makefile targets to get account ID automatically

- .gitlab/.gitlab-ci.yml
- idk/docker-compose.yml
- idk/ingest_test.go
When doing the release process, we generate version numbers that have a version tag but don't have a hash. The IDK test against the expected hash doesn't work in this context. Let's check for an expected tag first.
> handle tag-only commits with no hash in version

- idk/ingest_test.go
> off-by-v error in spelling of versions

- sql3/parser/parser.go
- sql3/parser/parser_test.go
- sql3/planner/opaltertable.go
- sql3/planner/opcreatetable.go
- sql3/test/defs/defs_create_table.go
parseOperand was assuming that any reference to MIN in a place where an operand was expected was a call, which it should be, but it might not be. parseCallExpression panics if it doesn't find a parenthesis, because it's never supposed to be called when we don't know we have one.
The test for this is in with MinMaxColumnConstraints, even though it's actually a test of MinMaxFunctionCalls, because that's where the other tests involving the special MIN/MAX tokens live.
> don't panic on a MIN that isn't a call

- sql3/planner/expressionanalyzer.go
- sql3/test/defs/defs_delete.go
- sql3/test/defs/defs_in.go
analyzeExpression - tupleLiteralExpression was covered by something else between the ticket getting filed and me starting on it. (*ExecutionPlanner).analyzeBinaryExpression now has increased coverage for IN / NOT IN. Several bugs got revealed by adding tests; those tests are commented out but can be re-enabled by whoever ends up working on the bugs. Tickets are filed.
> Add test coverage to expressionanalyzer.go

- sql3/parser/ast.go
- sql3/parser/parser_test.go
We forward-ported a handful of tests from the previous parser which relied on LIMIT clauses, but then we didn't support that. Now that we do, we uncomment most of these tests, and actually give them the correct data structures to compare with.
We leave two tests commented out. One was using `limit 10, 5` to express a limit plus offset, and the other is using `not fld = 1` as a WHERE clause, but we don't support unary-not to negate other expressions.
In the process, we discover that converting a SELECT with a LIMIT clause back to a string has a missing space, and fix that.
> uncomment old LIMIT tests, make them pass

- dax/test/dax/dax_test.go
- sql3/errors.go
- sql3/parser/ast.go
- sql3/parser/parser.go
- sql3/parser/walk.go
- sql3/planner/compileselect.go
- sql3/planner/expression.go
- sql3/planner/oppqldistinctscan.go
- sql3/planner/oppqlgroupby.go
- sql3/planner/oppqltablescan.go
- sql3/planner/planoptimizer.go
- sql3/test/defs/defs.go
- sql3/test/defs/defs_groupby.go
- sql3/test/defs/defs_top.go
This PR implements  query options hints that govern behavior for distinct and group by on set columns.
1. introduces syntax to support query hints on table source references `...from table_name with (hint(param))`
2. introduces the `flatten(column)` hint 
3. ensures `distinct` with and without flatten with a single set column ref works correctly
4. ensures `group by` with and without flatten with a single set column ref works correctly
> implemented query hints (flatten) (fb-2124)

- sql3/planner/compilecreatedatabase.go
statement without a units qualifier causes it to be set to 0
> CLOUD-1456: SERVERLESS - CREATE DATABASE

- sql3/planner/expression.go
This PR fixes a defect in the regex generation for `LIKE`.
> fix regex generation (fb-1640)

- dax/queryer/orchestrator.go
- dax/test/dax/dax_test.go
- executor.go
- executor_test.go
- field.go
- sql3/planner/expression.go
- sql3/planner/expressionagg.go
- sql3/planner/expressionpql.go
- sql3/planner/oppqlaggregate.go
- sql3/planner/planoptimizer.go
- sql3/test/defs/defs_aggregate.go
- sql3/test/defs/defs_join.go
no worries this one should be a simple one-liner, right?
actually it's four distinct bugs.
```
fbsql=# select percentile(x, 50) from i where x < 13;
------
5.00
fbsql=# select percentile(x, 50) from i where x < 13.0;
-------
10.00
```
In this, we see the following bugs:
1. With `where x < 13`, we actually use an SQL3-internal implementation of Percentile, rather than the PQL implementation, because `13` is an int64 and not a float64, and we don't allow int64 in Decimal conditions.
2. With `where x < 13.0`, the `WHERE` clause is not actually exported to the PQL Percentile call as a filter.
3. With or without the `WHERE` clause, PQL Percentile produces nonsense results (always the minimum, basically) for decimal fields.
4. The SQL3-internal implementation of Percentile is actually just a …
> make percentile work with where clauses and on decimal fields
